// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  accountSidebar: [{
    type: 'autogenerated',
    dirName: '.',
  }],
}

module.exports = sidebars
