const MAX_ORIGINAL_DIMENSION = 2048
const MAX_AUTO_TARGETS = 32
const THUMBNAIL_HEIGHT = 350
const LUMINANCE_HEIGHT = 640
const MIN_CONINESS = -2
const MAX_CONINESS = 2
const DEFAULT_CONINESS = 0
const DEFAULT_ARC_ANGLE = 180
const DEFAULT_TARGET_CIRCUMFERENCE = 100
const DISALLOWED_NAME_CHARACTERS = ['~', '^', '*', ';', '`', '<', '>']
const USER_METADATA_LIMIT = 2048
const MINIMUM_SHORT_LENGTH = 480
const MINIMUM_LONG_LENGTH = 640
const MAX_NAME_LENGTH = 255
const ALLOWED_UNITS = ['mm', 'in']

export {
  MAX_ORIGINAL_DIMENSION,
  MAX_AUTO_TARGETS,
  THUMBNAIL_HEIGHT,
  LUMINANCE_HEIGHT,
  MIN_CONINESS,
  MAX_CONINESS,
  DEFAULT_CONINESS,
  DEFAULT_ARC_ANGLE,
  DEFAULT_TARGET_CIRCUMFERENCE,
  DISALLOWED_NAME_CHARACTERS,
  USER_METADATA_LIMIT,
  MINIMUM_SHORT_LENGTH,
  MINIMUM_LONG_LENGTH,
  MAX_NAME_LENGTH,
  ALLOWED_UNITS,
}
