load("//bzl/js:js.bzl", "js_library")

package(default_visibility = ["//reality/cloud/aws/lambda/public-api:__subpackages__"])

js_library(
    name = "account",
    srcs = [
        "account.ts",
    ],
)

js_library(
    name = "pwa-info",
    srcs = [
        "pwa-info.ts",
    ],
)

js_library(
    name = "policyviolation",
    srcs = [
        "policyviolation.ts",
    ],
)

js_library(
    name = "account-short-names",
    srcs = [
        "account-short-names.ts",
    ],
)

js_library(
    name = "ad-submission",
    srcs = [
        "ad-submission.ts",
    ],
)

js_library(
    name = "contract",
    srcs = [
        "contract.ts",
    ],
)

js_library(
    name = "module-tag-map",
    srcs = [
        "module-tag-map.ts",
    ],
)

js_library(
    name = "init",
    srcs = [
        "init.ts",
    ],
    deps = [
        "//reality/cloud/aws/lambda/public-api/models:account",
        "//reality/cloud/aws/lambda/public-api/models:account-short-names",
        "//reality/cloud/aws/lambda/public-api/models:accountcontractagreement",
        "//reality/cloud/aws/lambda/public-api/models:ad-submission",
        "//reality/cloud/aws/lambda/public-api/models:api-key",
        "//reality/cloud/aws/lambda/public-api/models:app",
        "//reality/cloud/aws/lambda/public-api/models:apptag",
        "//reality/cloud/aws/lambda/public-api/models:apptagmap",
        "//reality/cloud/aws/lambda/public-api/models:contract",
        "//reality/cloud/aws/lambda/public-api/models:contractitem",
        "//reality/cloud/aws/lambda/public-api/models:contracttemplate",
        "//reality/cloud/aws/lambda/public-api/models:contracttier",
        "//reality/cloud/aws/lambda/public-api/models:cross-account-permission",
        "//reality/cloud/aws/lambda/public-api/models:dependency-set",
        "//reality/cloud/aws/lambda/public-api/models:discovery-app",
        "//reality/cloud/aws/lambda/public-api/models:featuredappimages",
        "//reality/cloud/aws/lambda/public-api/models:imagetarget",
        "//reality/cloud/aws/lambda/public-api/models:invite",
        "//reality/cloud/aws/lambda/public-api/models:module",
        "//reality/cloud/aws/lambda/public-api/models:module-tag-map",
        "//reality/cloud/aws/lambda/public-api/models:module-user",
        "//reality/cloud/aws/lambda/public-api/models:policyviolation",
        "//reality/cloud/aws/lambda/public-api/models:pwa-info",
        "//reality/cloud/aws/lambda/public-api/models:scheduled-subscription",
        "//reality/cloud/aws/lambda/public-api/models:user-account",
        "//reality/cloud/aws/lambda/public-api/models:user-app-prefs",
    ],
)

js_library(
    name = "module",
    srcs = [
        "module.ts",
    ],
)

js_library(
    name = "app",
    srcs = [
        "app.ts",
    ],
)

js_library(
    name = "user-app-prefs",
    srcs = [
        "user-app-prefs.ts",
    ],
)

js_library(
    name = "module-user",
    srcs = [
        "module-user.ts",
    ],
)

js_library(
    name = "apptagmap",
    srcs = [
        "apptagmap.ts",
    ],
)

js_library(
    name = "contracttier",
    srcs = [
        "contracttier.ts",
    ],
)

js_library(
    name = "cross-account-permission",
    srcs = [
        "cross-account-permission.ts",
    ],
)

js_library(
    name = "user-account",
    srcs = [
        "user-account.ts",
    ],
)

js_library(
    name = "invite",
    srcs = [
        "invite.ts",
    ],
)

js_library(
    name = "imagetarget",
    srcs = [
        "imagetarget.ts",
    ],
)

js_library(
    name = "scheduled-subscription",
    srcs = [
        "scheduled-subscription.ts",
    ],
)

js_library(
    name = "apptag",
    srcs = [
        "apptag.ts",
    ],
)

js_library(
    name = "contractitem",
    srcs = [
        "contractitem.ts",
    ],
)

js_library(
    name = "dependency-set",
    srcs = [
        "dependency-set.ts",
    ],
)

js_library(
    name = "api-key",
    srcs = [
        "api-key.ts",
    ],
)

js_library(
    name = "discovery-app",
    srcs = [
        "discovery-app.ts",
    ],
)

js_library(
    name = "featuredappimages",
    srcs = [
        "featuredappimages.ts",
    ],
)

js_library(
    name = "contracttemplate",
    srcs = [
        "contracttemplate.ts",
    ],
)

js_library(
    name = "accountcontractagreement",
    srcs = [
        "accountcontractagreement.ts",
    ],
)
