load("//bzl/js:js.bzl", "js_library")

package(default_visibility = ["//reality/cloud:shared"])

js_library(
    name = "cognito-config",
    srcs = [
        "cognito-config.js",
    ],
    deps = [
        "//reality/cloud/xrhome/src/shared:use-prod",
    ],
)

js_library(
    name = "use-prod",
    srcs = [
        "use-prod.js",
    ],
)

js_library(
    name = "time-utils",
    srcs = [
        "time-utils.ts",
    ],
)

js_library(
    name = "registry",
    srcs = [
        "registry.ts",
    ],
)

js_library(
    name = "repo-id",
    srcs = [
        "repo-id.ts",
    ],
)

js_library(
    name = "cms-constants",
    srcs = [
        "cms-constants.ts",
    ],
)

js_library(
    name = "xrrelease-config",
    srcs = [
        "xrrelease-config.js",
    ],
)

js_library(
    name = "signed-api-gateway",
    srcs = [
        "signed-api-gateway.ts",
    ],
)

js_library(
    name = "module-compatibility",
    srcs = [
        "module-compatibility.ts",
    ],
)

js_library(
    name = "pwa-utils",
    srcs = [
        "pwa-utils.js",
    ],
)

js_library(
    name = "pwa-constants",
    srcs = [
        "pwa-constants.js",
    ],
)

js_library(
    name = "project-specifier",
    srcs = [
        "project-specifier.ts",
    ],
)

js_library(
    name = "memory-cache",
    srcs = [
        "memory-cache.ts",
    ],
    deps = [
        "//reality/cloud/xrhome/src/shared:time-utils",
    ],
)

js_library(
    name = "user-editor-settings",
    srcs = [
        "user-editor-settings.ts",
    ],
)

js_library(
    name = "special-features",
    srcs = [
        "special-features.ts",
    ],
)

js_library(
    name = "tos",
    srcs = [
        "tos.ts",
    ],
)

js_library(
    name = "policy-violation-constants",
    srcs = [
        "policy-violation-constants.ts",
    ],
)
