// Based on https://sequelize.org/docs/v6/other-topics/typescript/

import type {ModelCtor, Model, Association} from 'sequelize'
import {singularize, pluralize} from 'inflection'

import {createDb} from '../src/shared/integration/db/db-impl'
import dbConfigForEnv from '../config/db'
import {PROPERTY_TYPE_OVERRIDES} from './definition-generation'

// @ts-ignore
const db = createDb(dbConfigForEnv('test'))

const generateHeader = () => `\
// This file was autogenerated using generate-model-definitions.ts

// npm run generate-model-definitions

// These definitions should only be used by server-side code.

/* eslint-disable max-classes-per-file, lines-between-class-members, camelcase, max-len, quotes */

import {
  Model, HasManyGetAssociationsMixinOptions, HasManySetAssociationsMixin,
  HasManyAddAssociationMixin, HasManyAddAssociationsMixin, HasManyHasAssociationMixin,
  HasManyCountAssociationsMixin, HasManyCreateAssociationMixin, HasManyRemoveAssociationMixin,
  HasManyRemoveAssociationsMixin, HasManyHasAssociationsMixin, HasOneGetAssociationMixinOptions,
  HasOneSetAssociationMixin, HasOneCreateAssociationMixin,
} from 'sequelize'

import type {DependenciesById} from '@nia/reality/shared/module/module-dependency'
import type {Permissions} from '@nia/reality/shared/nae/nae-types'

import type {TermsAgreements} from '../../tos'
import type {UserEditorSettings} from '../../user-editor-settings'
import type {SpecialFeatureFlag} from '../../special-features'
import type {GenerateRequestInput} from '../../genai/types/generate'

type GetMany<Model> = (options?: HasManyGetAssociationsMixinOptions) => Promise<Model[]>
type GetOne<Model> = (options?: HasOneGetAssociationMixinOptions) => Promise<Model>`

const generateAssociationDefinition = (association: Association) => {
  const type = association.associationType
  const singular = singularize(association.as)
  const plural = pluralize(association.as)
  const modelClass = association.target.name

  if (type === 'HasMany' || type === 'BelongsToMany') {
    return `

  public get${plural}!: GetMany<${modelClass}>
  public set${plural}!: HasManySetAssociationsMixin<${modelClass}, string>
  public add${singular}!: HasManyAddAssociationMixin<${modelClass}, string>
  public add${plural}!: HasManyAddAssociationsMixin<${modelClass}, string>
  public create${singular}!: HasManyCreateAssociationMixin<${modelClass}>
  public remove${singular}!: HasManyRemoveAssociationMixin<${modelClass}, string>
  public remove${plural}!: HasManyRemoveAssociationsMixin<${modelClass}, string>
  public has${singular}!: HasManyHasAssociationMixin<${modelClass}, string>
  public has${plural}!: HasManyHasAssociationsMixin<${modelClass}, string>
  public count${plural}!: HasManyCountAssociationsMixin

  public ${plural}?: ${modelClass}[]`
  } else if (type === 'HasOne' || type === 'BelongsTo') {
    return `

  public get${singular}!: GetOne<${modelClass}>
  public set${singular}!: HasOneSetAssociationMixin<${modelClass}, string>
  public create${singular}!: HasOneCreateAssociationMixin<${modelClass}>

  public ${singular}?: ${modelClass}`
  } else {
    throw new Error(`Unknown association type: ${type}`)
  }
}

const generatePropertyDefinition = (modelName: string, propertyName: string, definition: any) => {
  let typeString: string

  if (PROPERTY_TYPE_OVERRIDES[modelName]?.[propertyName]) {
    typeString = PROPERTY_TYPE_OVERRIDES[modelName][propertyName]
  } else {
    switch (definition?.type?.key) {
      case 'ENUM':
        typeString = definition.type.values.map(v => JSON.stringify(v)).join(' | ')
        break
      case 'BOOLEAN':
        typeString = 'boolean'
        break
      case 'FLOAT':
      case 'INTEGER':
      case 'BIGINT':
        typeString = 'number'
        break
      case 'UUID':
      case 'STRING':
      case 'TEXT':
        typeString = 'string'
        break
      case 'DATE':
        typeString = 'Date'
        break
      case 'JSONB':
        throw new Error(
          `Expected PROPERTY_TYPE_OVERRIDES for: Table: ${modelName} Property: ${propertyName}`
        )
      default:
        throw new Error(`Unable to export type for: Table: ${modelName} Property: ${propertyName}`)
    }
  }

  const allowNull = definition.allowNull || definition.allowNull === undefined

  // eslint-disable-next-line max-len, local-rules/multiline-ternary
  return `  public ${propertyName}!: ${allowNull ? `${typeString} | null` : `NonNullable<${typeString}>`}`
}

const generateModelDefinition = (modelName: string, model: ModelCtor<Model<any, any>>) => (
  `\nclass ${modelName} extends Model {
${Object.entries((model as any).tableAttributes).map(([name, definition]) => (
    generatePropertyDefinition(modelName, name, definition)
  )).join('\n')}${Object.values(model.associations).map(association => (
    generateAssociationDefinition(association)
  )).join('')}
}`
)

const generateFooter = (modelNames: string[]) => (
  `\nexport {
${modelNames.map(e => `  ${e},`).join('\n')}
}`
)

const generateModelDefinitions = () => {
  // eslint-disable-next-line no-console
  console.log(generateHeader())

  Object.keys(db.sequelize.models).forEach((name) => {
    // eslint-disable-next-line no-console
    console.log(generateModelDefinition(name, db.sequelize.models[name]))
  })

  // eslint-disable-next-line no-console
  console.log(generateFooter(Object.keys(db.sequelize.models)))
}

generateModelDefinitions()
