// Based on https://sequelize.org/v5/manual/typescript

import type {ModelCtor, Model} from 'sequelize'
import {pluralize} from 'inflection'

import {createDb} from '../src/shared/integration/db/db-impl'
import dbConfigForEnv from '../config/db'
import {PROPERTY_TYPE_OVERRIDES} from './definition-generation'

const db = createDb(dbConfigForEnv('test'))

const generateHeader = () => `\
// This file was autogenerated using generate-client-definitions.ts

// npm run generate-model-definitions

// These definitions represent what the database entries look like when they're sent over the wire.

// Since the client does extra processing before the data goes into redux, we define IApp for
// example which should generally be used instead of using App directly from db.ts.

/* eslint-disable camelcase, quotes, max-len */

import type {DependenciesById} from '../../../shared/module/module-dependency'
import type {TermsAgreements} from '../../../shared/tos'
import type {SpecialFeatureFlag} from '../../../shared/special-features'
import type {UserEditorSettings} from '../../../shared/user-editor-settings'
import type {GenerateRequestInput} from '../../../shared/genai/types/generate'
import type {Permissions} from '../../../shared/nae/nae-types'\n`

interface ExportEntry {
  identifier: string
  alias?: string
}

interface GenerationContext {
  afterLines: string[]
  exports: ExportEntry[]
}

const capitalizeFirst = (str: string) => (
  str.length === 0 ? str : str[0].toUpperCase() + str.substring(1)
)

const cleanName = (name: string) => name.replace(/_/g, '')

const generateEnum = (modelName: string, propertyName: string, definition: any) => {
  const name = `${cleanName(modelName)}${capitalizeFirst(propertyName)}`

  const fallbackName = `enum_${pluralize(modelName)}_${propertyName}`

  const declaration = `type ${name} = ${definition.type.values.map(
    (v: any) => JSON.stringify(v)
  ).join(' | ')}`

  return {name, fallbackName, declaration}
}

const generatePropertyDefinition = (
  context: GenerationContext, modelName: string, propertyName: string, definition: any
) => {
  let typeString: string

  if (PROPERTY_TYPE_OVERRIDES[modelName]?.[propertyName]) {
    typeString = PROPERTY_TYPE_OVERRIDES[modelName][propertyName]
  } else {
    switch (definition?.type?.key) {
      case 'ENUM': {
        const enumDefinition = generateEnum(modelName, propertyName, definition)
        context.afterLines.push(enumDefinition.declaration)
        context.exports.push({identifier: enumDefinition.name}, {
          identifier: enumDefinition.name,
          alias: enumDefinition.fallbackName,
        })
        typeString = enumDefinition.name
        break
      }
      case 'BOOLEAN':
        typeString = 'boolean'
        break
      case 'FLOAT':
      case 'INTEGER':
      case 'BIGINT':
        typeString = 'number'
        break
      case 'UUID':
      case 'STRING':
      case 'TEXT':
      case 'DATE':  // NOTE(christoph): Dates become strings when sent to the client
        typeString = 'string'
        break
      case 'JSONB':
        throw new Error(
          `Expected PROPERTY_TYPE_OVERRIDES for: Table: ${modelName} Property: ${propertyName}`
        )
      default:
        throw new Error(`Unable to export type for: Table: ${modelName} Property: ${propertyName}`)
    }
  }

  const allowNull = definition.allowNull || definition.allowNull === undefined

  return `  ${propertyName}: ${allowNull ? `${typeString} | null` : `NonNullable<${typeString}>`}`
}

const generateModelDefinition = (
  context: GenerationContext, modelName: string, model: ModelCtor<Model<any, any>>
) => {
  const identifier = cleanName(modelName)
  context.exports.push({identifier})

  if (modelName !== identifier) {
    context.exports.push({identifier, alias: modelName})
  }

  const pluralForm = pluralize(modelName)
  if (pluralForm !== modelName) {
    context.exports.push({identifier, alias: pluralForm})
  }

  const properties = Object.entries((model as any).tableAttributes).map(([name, definition]) => (
    generatePropertyDefinition(context, modelName, name, definition)
  ))

  return `interface ${identifier} {
${properties.join('\n')}
}\n`
}

const generateTablesDefinition = (context: GenerationContext, modelNames: string[]) => {
  context.exports.push({identifier: 'Tables'})
  return `interface Tables {
${modelNames
    .map((modelName) => {
      const cleanModelName = cleanName(modelName)
      return `  ${pluralize(cleanModelName)}: ${cleanModelName}`
    })
    .join('\n')}
}\n`
}

// It's better if the main exports are first, then the fallback aliases are after, and alphabetized
// within.
const sortExports = (exports: ExportEntry[]) => exports.sort((a, b) => {
  if (a.alias && !b.alias) {
    return 1
  } else if (b.alias && !a.alias) {
    return -1
  } else {
    return a.identifier.localeCompare(b.identifier)
  }
})

const generateExports = (exports: ExportEntry[]) => (
  `\nexport type {
${exports.map(({alias, identifier}) => `  ${identifier}${alias ? ` as ${alias}` : ''},`).join('\n')}
}`
)

const generateModelDefinitions = () => {
  const context: GenerationContext = {afterLines: [], exports: []}

  // eslint-disable-next-line no-console
  console.log(generateHeader())

  const models = Object.keys(db.sequelize.models)

  models.forEach((name) => {
    // eslint-disable-next-line no-console
    console.log(generateModelDefinition(context, name, db.sequelize.models[name]))
  })

  // eslint-disable-next-line no-console
  console.log(generateTablesDefinition(context, models))

  // eslint-disable-next-line no-console
  context.afterLines.forEach(e => console.log(e))

  // eslint-disable-next-line no-console
  console.log(generateExports(sortExports(context.exports)))
}

generateModelDefinitions()
