// Copyright (c) 2021 8th Wall, Inc.
// Original Author: Lynn Dang (lynn@8thwall.com)
//
// Mobile Depth View is used for visualizing and analyzing depthnet models on JS, to see how it
// performs on the phone.

#include "bzl/inliner/rules2.h"

cc_library {
  hdrs = {
    "mobile-depth-view.h",
  };
  deps = {
    "//apps/client/internalqa/omniscope/native:omniscope-view",
    "//apps/client/internalqa/omniscope/native/lib:viewdata",
    "//c8:c8-log",
    "//c8:color",
    "//c8:string",
    "//c8:vector",
    "//c8/geometry:intrinsics",
    "//c8/pixels:draw2",
    "//c8/pixels:draw2-widgets",
    "//c8/pixels/opengl:gl-error",
    "//c8/protolog:xr-requests",
    "//c8/stats:scope-timer",
    "//c8/time:rolling-framerate",
    "//reality/engine/depth:depthnet-depth-map",
    "//reality/engine/depth/data:embedded-depthnet",
  };
}
cc_end(0xa0a9e1cf);

#include "apps/client/internalqa/omniscope/native/lib/viewdata.h"
#include "apps/client/internalqa/omniscope/native/views/sensors/mobile-depth-view.h"
#include "c8/c8-log.h"
#include "c8/color.h"
#include "c8/geometry/intrinsics.h"
#include "c8/pixels/draw2-widgets.h"
#include "c8/pixels/draw2.h"
#include "c8/pixels/opengl/gl-error.h"
#include "c8/pixels/pixel-transforms.h"
#include "c8/protolog/xr-requests.h"
#include "c8/stats/scope-timer.h"
#include "reality/engine/depth/data/embedded-depthnet.h"

namespace c8 {

namespace {
class RenderData : public CpuProcessingResult {
public:
  uint32_t frameNumber = 0;

  // Holds the depth map generated by the depthnet model.
  RGBA8888PlanePixelBuffer depthNetMap;

  double fps;
};
}  // namespace

MobileDepthView::MobileDepthView() { copyTexture_ = compileCopyTexture2D(); }

void MobileDepthView::configure(const AppConfiguration &appConfig) {
  appConfig_ = appConfig;

  if (depthnet_ == nullptr) {
    const Vector<uint8_t> tfliteFile(
      embeddedDepthnetTfliteData, embeddedDepthnetTfliteData + embeddedDepthnetTfliteSize);
    depthnet_.reset(new Depthnet(tfliteFile));
  }
}

void MobileDepthView::initialize(std::unique_ptr<OmniscopeViewData> &dataPtr) {
  dataPtr = ViewDataGen::sceneRenderer<RenderData>(
    appConfig_, appConfig_.captureWidth, appConfig_.captureHeight);
  dataPtr->addProducer(
    std::make_unique<CameraPreviewDataProducer>(appConfig_, 192, 256, &copyTexture_));
}

void MobileDepthView::processCpu(OmniscopeViewData *data) {
  ScopeTimer t("process-cpu");
  auto &renderData = data->cpuProcessingResult<RenderData>();
  renderData = {};

  // Processing depths from depthnet.
  {
    ScopeTimer t2("depthnet-depth-map");
    // Get frame to feed into depthnet.
    auto originalImgPix = data->producer<CameraPreviewDataProducer>().cameraPreview();
    // Get depths from depthnet.
    DepthFloatPixels depthPix = depthnet_->detectDepth(originalImgPix);

    // Set up depth image display.
    // Allocate buffer if necessary.
    if (
      renderData.depthNetMap.pixels().rows() != depthPix.rows()
      || renderData.depthNetMap.pixels().cols() != depthPix.cols()) {
      renderData.depthNetMap = RGBA8888PlanePixelBuffer(depthPix.rows(), depthPix.cols());
    }
    auto depthNetPix = renderData.depthNetMap.pixels();
    // Range from 0 - 3/15 since the ARKit displayed range is from 0-5m when the
    // clipped max is 15 meters.
    floatToRgbaGray(depthPix, &depthNetPix, 0, 3.0 / 15);
  }
  rollingFramerate_.push();
  renderData.fps = rollingFramerate_.fps();
  renderData.frameNumber = frameNumber_++;
}

void MobileDepthView::initializeScene(OmniscopeViewData *data) {
  if (renderer_ != nullptr) {  // Already initialized.
    return;
  }

  C8Log("[mobile-depth-view] Initialized");

  int renderWidth = data->captureWidth();
  int renderHeight = data->captureHeight();

  // Set default to show depth.
  hideDepth_ = false;
  renderer_ = std::make_unique<Renderer>();
  // Set the default renderSpec on the root scene.
  scene().setRenderSpecs({{renderWidth, renderHeight}});

  // Create a scene camera with field of view matched to the device. For omniscope, this must have
  // flipY() applied.
  auto captureIntrinsics = Intrinsics::getCameraIntrinsics(appConfig_.deviceModel);
  scene().add(ObGen::perspectiveCamera(captureIntrinsics, renderWidth, renderHeight)).flipY();

  auto &depthnetFeed =
    scene()
      .add(
        ObGen::positioned(
          ObGen::named(ObGen::backQuad(), "depthnet-feed"), HMatrixGen::scaleY(1.0f)))
      .setMaterial(MatGen::image());
  depthnetFeed.geometry().setColor(Color::GRAY_05);

  auto quadPos =
    HMatrixGen::translation(-0.6f, -0.8f, -1.0f) * HMatrixGen::HMatrixGen::scale(0.35f, 0.1f, 0.0f);
  scene()
    .add(ObGen::named(ObGen::positioned(ObGen::backQuad(), quadPos), "tracking-status"))
    .setMaterial(MatGen::image());
}

void MobileDepthView::updateScene(OmniscopeViewData *data) {
  auto &renderData = data->cpuProcessingResult<RenderData>();
  const auto &depthNetMap = renderData.depthNetMap;

  // Switches between depth and camera feed
  if (!hideDepth_) {
    scene()
      .find<Renderable>("depthnet-feed")
      .material()
      .colorTexture()
      ->setRgbaPixels(depthNetMap.pixels());
  } else {
    scene()
      .find<Renderable>("depthnet-feed")
      .material()
      .colorTexture()
      ->setNativeId(data->cameraTexture());
  }

  {
    RGBA8888PlanePixelBuffer buffer(70, 300);
    auto cp = buffer.pixels();
    fill(Color::OFF_WHITE, cp);

    textBox(
      {
        format("Num frames: %d", renderData.frameNumber + 1),
        format("FPS: %f", renderData.fps),
      },
      {0.0f, 0.0f},
      300,
      cp);
    scene()
      .find<Renderable>("tracking-status")
      .material()
      .colorTexture()
      ->setRgbaPixelBuffer(std::move(buffer));
  }
}

void MobileDepthView::resetScene() { std::lock_guard<std::mutex> lock(touchMtx_); }

void MobileDepthView::renderDisplay(OmniscopeViewData *data) {
  ScopeTimer t("render-display");

  initializeScene(data);  // Create the scene if needed.

  // Check if there is a new frame, or if the user input changed the result.
  if (!updateSceneWithUserInput() && lastUpdateTime_ == data->timeNanos()) {
    return;  // Nothing to rerender.
  }

  lastUpdateTime_ = data->timeNanos();

  updateScene(data);

  // Render the scene.
  data->renderer<Object8Renderer>().render(*renderer_, scene());
}

bool MobileDepthView::updateSceneWithUserInput() {
  if (scene().needsRerender()) {
    scene().setNeedsRerender(false);
    return true;
  }
  return false;  // Only update if needed.
}

void MobileDepthView::gotTouches(const Vector<Touch> &touches) { hideDepth_ = !hideDepth_; }

}  // namespace c8
