import {MILLISECONDS_PER_MINUTE} from '../time-utils'

// Niantic Auth has an internal mapping of 8th Wall APP_KEY <=> GAR_APP_ID
const NIANTIC_AUTH_APP_KEY = 'eighth-wall'

// TODO(wayne): TBD
const COGNITO_AUTH_PROVIDER_ID = 'cognito'
const GOOGLE_AUTH_PROVIDER_ID = 'google'
const APPLE_AUTH_PROVIDER_ID = 'apple'
const LOGIN_PROVIDERS = [
  COGNITO_AUTH_PROVIDER_ID,
  GOOGLE_AUTH_PROVIDER_ID,
  APPLE_AUTH_PROVIDER_ID,
] as const

const ACCESS_TOKEN_REFRESH_TIME = 45 * MILLISECONDS_PER_MINUTE

const LOGIN_TOKEN_DDB_TABLE_NAME = 'login-token'
const LOGIN_TOKEN_DDB_TABLE_USER_UUID_INDEX = 'userUuid-index'
const MAX_LOGIN_TOKENS_PER_USER = 10
const LOGIN_TOKEN_EXPIRATION = 5 * MILLISECONDS_PER_MINUTE
// LOGIN_TOKEN_REFRESH_TIME is used to refresh the Scaniverse login QR code
const LOGIN_TOKEN_REFRESH_TIME = LOGIN_TOKEN_EXPIRATION * 0.2

const FIRST_PUBLISHING_EMAIL_ROLLOUT_DATE = '2020-03-20'

export {
  NIANTIC_AUTH_APP_KEY,
  COGNITO_AUTH_PROVIDER_ID,
  GOOGLE_AUTH_PROVIDER_ID,
  APPLE_AUTH_PROVIDER_ID,
  LOGIN_PROVIDERS,
  ACCESS_TOKEN_REFRESH_TIME,
  LOGIN_TOKEN_DDB_TABLE_NAME,
  LOGIN_TOKEN_DDB_TABLE_USER_UUID_INDEX,
  MAX_LOGIN_TOKENS_PER_USER,
  LOGIN_TOKEN_EXPIRATION,
  LOGIN_TOKEN_REFRESH_TIME,
  FIRST_PUBLISHING_EMAIL_ROLLOUT_DATE,
}
