load("//bzl/js:js.bzl", "js_library")

package(default_visibility = ["//reality/cloud:shared"])

js_library(
    name = "rds",
    srcs = [
        "rds/global-bundle.pem.d.ts",
        "rds/global-bundle.pem.js",
    ],
)
