load("//bzl/capnproto:capnproto.bzl", "capnp_library")

package(default_visibility = ["//reality/quality:__subpackages__"])

capnp_library(
    name = "ground-homography-labels",
    srcs = [
        "ground-homography-labels.capnp",
    ],
    deps = [
    ],
)
