load("//bzl/js:js.bzl", "js_library")

package(default_visibility = [
    "//reality/cloud/studiohub:__subpackages__",
])

js_library(
    name = "mcp-websocket-server",
    srcs = [
        "mcp-websocket-server.ts",
    ],
)
