load("//bzl/js:js.bzl", "js_library")

js_library(
    name = "resource-constants",
    srcs = [
        "resource-constants.ts",
    ],
    visibility = [
        "//reality/app/nae/packager:__subpackages__",
    ],
)
