package(
    default_visibility = [
        "//apps/client/internalqa/omniscope:__subpackages__",
    ],
)

filegroup(
    name = "img",
    srcs = [
        "19CrimeFull.jpg",
        "a-sunday-on-la-grande-jatte-seurat.jpg",
        "a-sunday-on-la-grande-jatte-seurat_rotated.jpg",
        "amity.jpg",
        "biz-card.png",
        "claude-monet-painting-in-his-garden-at-argenteuil-renoir.jpg",
        "cornhole.jpg",
        "crystal-dew.jpg",
        "diamond.jpg",
        "dragon.jpg",
        "dumelaBrew.jpg",
        "flower-big.jpg",
        "icon-ar-camera.png",
        "inspectorstest.jpg",
        "mona-lisa-da-vinci.jpg",
        "osha.jpg",
        "pop-space.png",
        "postcard.png",
        "rocket-website.png",
        "saxjensen.jpg",
        "starry-night-van-gough.jpg",
        "sunglasses-big.jpg",
        "tulip-fields-in-holland-monet.jpg",
        "tully.jpg",
        "tully_rotated.jpg",
        "tyrell.jpg",
        "unconedTeaParty_l530t0w486h648.jpg",
    ],
)
