// Copied from core/omni.ts
// TODO(dat): move types into a separate module that core this module can depends on
const ImageTargetType = {
  PLANAR: 'PLANAR',
  CYLINDER: 'CYLINDER',
  UNSPECIFIED: 'UNSPECIFIED',
}

// TODO(nb): move to index.js
const images = [
  // { name: 'sunglasses',     imageUrl: '../img/sunglasses-big.jpg', },
  // { name: 'anime',          imageUrl: '../img/crystal-dew.jpg', },
  // { name: 'flower',         imageUrl: '../img/flower-big.jpg', },
  // { name: 'watarun',        imageUrl: '../img/wat-arun.jpg', },
  // { name: 'biz-card',       imageUrl: '../img/biz-card.png', },
  // { name: 'cornhole',       imageUrl: '../img/cornhole.jpg', },
  // { name: 'crystal-dew',    imageUrl: '../img/crystal-dew.jpg', },
  // { name: 'diamond',        imageUrl: '../img/diamond.jpg', },
  // { name: 'dragon',         imageUrl: '../img/dragon.jpg', },
  // { name: 'flower-big',     imageUrl: '../img/flower-big.jpg', },
  // { name: 'icon-ar-camera', imageUrl: '../img/icon-ar-camera.png', },
  // { name: 'inspectorstest', imageUrl: '../img/inspectorstest.jpg', },
  // { name: 'osha',           imageUrl: '../img/osha.jpg', },
  // { name: 'pop-space',      imageUrl: '../img/pop-space.png', },
  // { name: 'postcard',       imageUrl: '../img/postcard.png', },
  // { name: 'rocket-website', imageUrl: '../img/rocket-website.png', },
  // { name: 'sunglasses-big', imageUrl: '../img/sunglasses-big.jpg', },
  // { name: 'watarun',        imageUrl: '../img/wat-arun.jpg', },
  // {
  //   name: 'claude-monet-painting-in-his-garden-at-argenteuil-renoir',
  //   imageUrl: '../img/claude-monet-painting-in-his-garden-at-argenteuil-renoir.jpg',
  // },
  // { name: 'mona-lisa-da-vinci', imageUrl: '../img/mona-lisa-da-vinci.jpg', },
  // {
  //   name: 'tulip-fields-in-holland-monet', imageUrl: '../img/tulip-fields-in-holland-monet.jpg',
  // },
  // { name: 'starry-night-van-gough', imageUrl: '../img/starry-night-van-gough.jpg', },
  // {
  //  name: 'a-sunday-on-la-grande-jatte-seurat',
  //  imageUrl: '../img/a-sunday-on-la-grande-jatte-seurat.jpg',
  // },
  // {
  //   name: 'a-sunday-on-la-grande-jatte-seurat_rotated',
  //   imageUrl: '../img/a-sunday-on-la-grande-jatte-seurat_rotated.jpg',
  //   isRotated: true,
  // },
  {
    name: 'tyrell',
    imageUrl: '../img/tyrell.jpg',
    type: ImageTargetType.CYLINDER,
    cylinderCircumferenceTop: 26.0,
    cylinderCircumferenceBottom: 26.0,
    cylinderSideLength: 11,
    targetCircumferenceTop: 8.5,
  },
  {
    name: 'tully',
    imageUrl: '../img/tully.jpg',
    type: ImageTargetType.CYLINDER,
    cylinderCircumferenceTop: 260.0,
    cylinderCircumferenceBottom: 260.0,
    cylinderSideLength: 109.83,
    targetCircumferenceTop: 85,
  },
  // {
  //   name: 'tully_rotated',
  //   imageUrl: '../img/tully_rotated.jpg',
  //   type: ImageTargetType.CYLINDER,
  //   cylinderCircumferenceTop: 260,
  //   cylinderCircumferenceBottom: 260,
  //   cylinderSideLength: 109.83,
  //   targetCircumferenceTop: 85,
  //   originalImageWidth: 960,
  //   originalImageHeight: 743,
  //   cropOriginalImageX: 322,
  //   cropOriginalImageY: 4,
  //   cropOriginalImageWidth: 536,
  //   cropOriginalImageHeight: 714,
  //   isRotated: true,
  // },
  // {
  //   name: 'amity',
  //   imageUrl: '../img/amity.jpg',
  //   type: ImageTargetType.CYLINDER,
  //   cylinderCircumferenceTop: 27.3,
  //   cylinderCircumferenceBottom: 27.3,
  //   cylinderSideLength: 12.9,
  //   targetCircumferenceTop: 10.9,
  // },
  // {
  //   name: 'amity_crop_omni',
  //   imageUrl: '../img/amity_crop_omni.jpg',
  //   type: ImageTargetType.CYLINDER,
  //   cylinderCircumferenceTop: 273,
  //   cylinderCircumferenceBottom: 273,
  //   cylinderSideLength: 127.57,
  //   targetCircumferenceTop: 109,
  //   originalImageWidth: 1278,
  //   originalImageHeight: 1092,
  //   cropOriginalImageX: 98,
  //   cropOriginalImageY: 41,
  //   cropOriginalImageWidth: 898,
  //   cropOriginalImageHeight: 1197,
  //   isRotated: false,
  // },
  // {
  //   name: 'amity_rotated',
  //   imageUrl: '../img/amity_rotated.jpg',
  //   type: ImageTargetType.CYLINDER,
  //   cylinderCircumferenceTop: 27.3,
  //   cylinderCircumferenceBottom: 27.3,
  //   cylinderSideLength: 12.9,
  //   targetCircumferenceTop: 10.9,
  //   originalImageWidth: 1278,
  //   originalImageHeight: 1092,
  //   cropOriginalImageX: 244,
  //   cropOriginalImageY: 0,
  //   cropOriginalImageWidth: 819,
  //   cropOriginalImageHeight: 1092,
  //   isRotated: true,
  // },
]

export {
  images,
}
