package(default_visibility = [
    "//reality/quality/benchmark:__subpackages__",
    "//reality/quality/synthetic:__subpackages__",
])

filegroup(
    name = "assets",
    srcs = [
        "carpet.jpg",
        "crate.jpg",
        "cubemap1.jpg",
        "cubemap2.png",
        "cubemap3.jpg",
        "ground.jpg",
        "table.jpg",
    ],
)
