#!/bin/bash

echo "
┌────────────────────────────────────────────┐
│        This functionality has moved        │
├────────────────────────────────────────────┤
│                                            │
│    You can now land to prod8/cdn/web to    │
│             upload to the cdn.             │
│                                            │
└────────────────────────────────────────────┘
"
