fn main() {

    // simple debug boolean variable
    let debug = false;

    // Define General Variables
    // Iterate over the arguments and save the in a vector
    let args: Vec<String> = std::env::args().skip(1).collect();

    // Number of arguments
    // let number_of_arguments = args.len();

    // Create a new vector of strings to store the actual arguments, by default copying from the original args
    let mut actual_args: Vec<String> = args;
    
    // Check if the first argument is a clang response file by checking if it starts with @
    // NOTE: We are expecting this only for the linker (as it supported by bazel), not for the compiler
    let is_clang_response_file = actual_args[0].starts_with("@");

    // initialize the response_file path to empty string
    let mut response_file = String::new();
    
    // If the first argument is a clang response file, then I read the file and split it by spaces and save it in args
    if is_clang_response_file {

        // We assume that the each arg is a new line of the file, because it was observed in the response file generated by bazel
        // however this is not always true in general (llvm documentation simply specify args separated by spaces)
        let arg_separator = "\n";

        response_file = actual_args[0].clone().replace("@", "");
        let response_file_content = std::fs::read_to_string(response_file.clone()).expect(format!("Error reading response file: {}", response_file.clone()).as_str());
        let response_file_args: Vec<String> = response_file_content.split(arg_separator).map(|s| s.to_string()).collect();
        let mut new_args: Vec<String> = Vec::new();
        for argument in response_file_args.iter() {
            new_args.push(argument.clone());
        }
        for argument in actual_args.iter().skip(1) {
            new_args.push(argument.clone());
        }
        
        // replace args with new_args
        actual_args = new_args;
    }

    // Get value of WORKSPACE_ENV env variable
    let workspace_env = std::env::var("WORKSPACE_ENV").unwrap();

    // get value of LLVM_USR env variable
    let llvm_usr = std::env::var("LLVM_USR").unwrap();

    // Output index as int
    let mut output_index: usize = 0;

    // Metadata index as int
    let mut metadata_index = 0;

    // Iterate over the arguments and save the output_name index
    for (index, argument) in actual_args.iter().enumerate() {
        if argument == "-o" {
            output_index = index + 1;
        }
        if argument == "-MF" {
            metadata_index = index + 1;
        }
    }

    // String for the output name
    let output_name = actual_args[output_index].clone();

    // Load json from file path in workspace_env variable if
    let json_string = std::fs::read_to_string(workspace_env.clone()).expect(format!("Error reading workspace-env file: {}", workspace_env.clone()).as_str());
    // Load json serde value
    let json_value: serde_json::Value = serde_json::from_str(json_string.as_str()).expect(format!("Error parsing json in workspace-env file: {}", workspace_env.clone()).as_str());

    // let bazel_execution_root = json_value["BAZEL_EXECUTION_ROOT"].as_str().unwrap();
    let bazel_output_base = json_value["BAZEL_OUTPUT_BASE"].as_str().unwrap();
    // let bazel_workspace = json_value["BAZEL_WORKSPACE"].as_str().unwrap();

    // if bazel_output_base starts with /c/ then I replace it with c:/ and save it in bazel_output_base
    let bazel_output_base = if bazel_output_base.clone().starts_with("/c/") {
        bazel_output_base.clone().replace("/c/", "c:/")
    } else {
        bazel_output_base.clone().to_string()
    };

    // Get current directory of the process
    let current_sandbox_directory = std::env::current_dir().unwrap();

    // if current_sandbox_directory starts (sometime it does, sometime it does not) with /c/ then I replace it with c:/ and save it in bazel_output_base
    let current_sandbox_directory = if current_sandbox_directory.clone().to_str().unwrap().starts_with("/c/") {
        current_sandbox_directory.clone().to_str().unwrap().replace("/c/", "c:/")
    } else {
        current_sandbox_directory.clone().to_str().unwrap().to_string()
    };

    // Get exec dir from current_directory by applying sed expression "/sandbox/[^/]*\/[0-9]*"
    let exec_dir = current_sandbox_directory.replace(r"/sandbox/[^/]*\/[0-9]*", "");

    // I iterate over the arguments and replace bazel_output_base with escaped_bazel_output_base
    // if is_clang_response_file is true, then I will iterate write the new arguments in a new response file
    // otherwise I will just store in a new vector of strings
    let mut new_args: Vec<String> = Vec::new();

    // if exec_dir is different from current_sandbox_directory, then we add a --file-prefix-map=$current_sandbox_directory
    if exec_dir != current_sandbox_directory {
        new_args.push(format!("-ffile-prefix-map={}=", current_sandbox_directory.clone()))    
    }

    // Append to file_prefix_map_flag also bazel_output_base/external=external
    new_args.push(format!("-ffile-prefix-map={}={}", bazel_output_base, "external"));

    for argument in actual_args.iter() {

        // if current_sandbox_directory starts with /c/ (sometime it does, sometime it does not) then I replace it with c:/ and save it in bazel_output_base
        let argument = if argument.clone().starts_with("/c/") {
            argument.clone().replace("/c/", "c:/")
        } else {
            argument.clone().to_string()
        };
        new_args.push(argument.replace("BAZEL_OUTPUT_BASE", bazel_output_base.as_str()));
    }

    if is_clang_response_file {
        let new_response_file = format!("{}.for_clang_native_wrapper", response_file.clone());
        std::fs::write(new_response_file.clone(), new_args.join("\n")).expect(format!("Error writing file: {}", new_response_file.clone()).as_str());

        // I empty the new_args vector and just use the response file as the first argument
        new_args = Vec::new();
        new_args.push(format!("@{}", new_response_file.clone()));
    }

    // I run a process to call clang as follows:
    // $bazel_output_base/$llvm_usr/bin/clang $file_prefix_map_flag $new_args
    // and printing all stdout and stderr

    let actual_tool = "clang.exe";
    let actual_tool_in_path = format!(
        "{bazel_output_base}/{llvm_usr}/bin/{actual_tool}",
        bazel_output_base = bazel_output_base,
        llvm_usr = llvm_usr,
        actual_tool = actual_tool);

    if debug {
        let actual_command = format!(
            "{actual_tool_in_path} {new_args}",
            actual_tool_in_path = actual_tool_in_path,
            new_args = new_args.join(" "));

        println!("========= {actual_tool} command ========\n{actual_command}",
            actual_tool = actual_tool,
            actual_command = actual_command);

        let output_name_commang_debug = output_name.clone() + "_clang-windows-wrapper-native_debug.txt";
        println!("========= Writing command to file: {output_name_commang_debug}",
            output_name_commang_debug = output_name_commang_debug);

        std::fs::write(output_name_commang_debug.clone(),
                       actual_command).expect(format!("Error writing file: {}", output_name_commang_debug.clone()).as_str());
    }

    let clang_output = std::process::Command::new(format!("{}/{}/bin/{}", bazel_output_base, llvm_usr, actual_tool))
        .args(new_args)
        .output()
        .expect("Failed to execute clang.");

    // I print stdout and stderr of clang only if the are not empty
    if !clang_output.stdout.is_empty() {
        println!("========= clang stdout ========\n{}", String::from_utf8(clang_output.stdout).unwrap());
    }
    if !clang_output.stderr.is_empty() {
        println!("========= clang stderr ========:\n{}", String::from_utf8(clang_output.stderr).unwrap());
    }

    // if the metafile_path exists, then I read it and replace bazel_output_base with {{deceive_bazel_header_deps}}

    if debug {
        println!("============= metafile_index {}", metadata_index);
    }

    if metadata_index > 0 {
        let metafile_path = actual_args[metadata_index].clone();

        if std::path::Path::new(metafile_path.clone().as_str()).exists() && metadata_index > 0 {

            // Get metafile path at metadata_index of args, make a backup copy .bak and substitute the contents of the original everywhere is $escaped_bazel_output_base with the string "{{deceive_bazel_header_deps}}"
            std::fs::copy(metafile_path.clone(), format!("{}.bak", metafile_path.clone())).expect(format!("Error copying file: {}", metafile_path.clone()).as_str());

            if debug {
                println!("============= metafile_path {}", metafile_path.to_lowercase());
            }

            let metafile_string = std::fs::read_to_string(metafile_path.clone()).expect(format!("Error reading file: {}", metafile_path.clone()).as_str());
            if debug {
                println!("============= metafile contents \n{}", metafile_string.to_lowercase());
            }
            let winpath_sep_bazel_output_base = bazel_output_base.clone().replace("/", r"\").to_lowercase();
            if debug {
                println!("----- replace {} with {{deceive_bazel_header_deps}} in the following:\n {}", winpath_sep_bazel_output_base.as_str(), metafile_string.to_lowercase());
            }
            let metafile_string = metafile_string.to_lowercase().replace(winpath_sep_bazel_output_base.as_str(), "/{{deceive_bazel_header_deps}}");
            if debug {
                println!("----- replace {} with {{deceive_bazel_header_deps}} in the following:\n{}", bazel_output_base.as_str().to_lowercase(), metafile_string.to_lowercase());
            }

            let metafile_string = metafile_string.to_lowercase().replace(bazel_output_base.as_str(), "/{{deceive_bazel_header_deps}}");
            std::fs::write(metafile_path.clone(), metafile_string).expect(format!("Error writing file: {}", metafile_path.clone()).as_str());
            return;
        }
    }
}
