const MAX_SUPPORT_FORM_ATTACHMENTS_ALLOWED = 5
const SUPPORT_FORM_ACCEPTED_FILE_TYPES = ['.jpeg', '.jpg', '.png'] as const

export {
  MAX_SUPPORT_FORM_ATTACHMENTS_ALLOWED,
  SUPPORT_FORM_ACCEPTED_FILE_TYPES,
}
