"""Rule to upload md generated by stardoc to confluence.
"""
def _upload_md_to_confluence_page_impl(ctx):
  
  confluence_page_id_out = ctx.actions.declare_file("{}.confluence_page_id".format(ctx.attr.name)) 

  if len(ctx.attr.md.files.to_list()) > 1:
    print("WARNING: Current upload_md_to_confluence_page rule only supports a single markdown file per target. Only the first file ({}) will be used.".format(ctx.attr.md.files.to_list()[0]))

  single_md_file = ctx.attr.md.files.to_list()[0]
  
  ctx.actions.run_shell(
    inputs = [single_md_file] + ctx.attr.markdown2confluence_toolset.files.to_list(),
    outputs = [confluence_page_id_out],
    command = "{markdown2confluence_tool} -d --parent \"{confluence_parent_page_id}\" --space \"{confluence_space}\" --title \"{confluence_page_title}\" \"{md}\" | tee \"{confluence_page_id_out}\"".format(
      markdown2confluence_tool = ctx.attr.markdown2confluence_toolset.files.to_list()[0].path,
      confluence_parent_page_id = ctx.attr.confluence_parent_page_id,
      confluence_space = ctx.attr.confluence_space,
      confluence_page_title = ctx.attr.confluence_page_title,
      md = single_md_file.path,
      confluence_page_id_out = confluence_page_id_out.path,
    ),
    execution_requirements = {
      "local": "1",
      "no-cache": "1",
    },
  )

  return [
    DefaultInfo(files = depset([confluence_page_id_out])),
  ]


_upload_md_to_confluence_page = rule(
  implementation = _upload_md_to_confluence_page_impl,
  attrs = {
    "confluence_parent_page_id": attr.string(
      mandatory = True,
    ),
    "confluence_space": attr.string(
      mandatory = True,
    ),
    "confluence_page_title": attr.string(
      mandatory = True,
    ),
    "md": attr.label(
      mandatory = True,
    ),
    "markdown2confluence_toolset": attr.label(
      default = Label("@markdown2confluence//:markdown2confluence_toolset"),
    ),
  },
  doc = "Upload markdown file generated by a @stardoc//stardoc:stardoc.bzl rule to confluence page",
)

def upload_md_to_confluence_page(name, **kwargs):
  _upload_md_to_confluence_page(
    name = name, 
    target_compatible_with = ["@markdown2confluence//:host_supported"], 
    **kwargs
  )