java_library(
    name = "annotations",
    srcs = [
        "DoNotStrip.java",
        "Nullable.java",
        "UsedByNative.java",
        "UsedByReflection.java",
        "VisibleForTesting.java",
    ],
    visibility = [
        "//visibility:public",
    ],
)
