package(default_visibility = [
    "//reality/quality/visualization/protolog:__subpackages__",
])

filegroup(
    name = "reader-test-data",
    testonly = 1,
    srcs = [
        "capture.json",
        "empty_log",
        "frame_0.jpg",
        "frame_1.jpg",
        "frame_2.jpg",
    ],
)
