// This file was autogenerated using generate-model-definitions.ts

// npm run generate-model-definitions

// These definitions should only be used by server-side code.

/* eslint-disable max-classes-per-file, lines-between-class-members, camelcase, max-len, quotes */

import {
  Model, HasManyGetAssociationsMixinOptions, HasManySetAssociationsMixin,
  HasManyAddAssociationMixin, HasManyAddAssociationsMixin, HasManyHasAssociationMixin,
  HasManyCountAssociationsMixin, HasManyCreateAssociationMixin, HasManyRemoveAssociationMixin,
  HasManyRemoveAssociationsMixin, HasManyHasAssociationsMixin, HasOneGetAssociationMixinOptions,
  HasOneSetAssociationMixin, HasOneCreateAssociationMixin,
} from 'sequelize'

import type {DependenciesById} from '@nia/reality/shared/module/module-dependency'
import type {Permissions} from '@nia/reality/shared/nae/nae-types'

import type {TermsAgreements} from '../../tos'
import type {UserEditorSettings} from '../../user-editor-settings'
import type {SpecialFeatureFlag} from '../../special-features'
import type {GenerateRequestInput} from '../../genai/types/generate'

type GetMany<Model> = (options?: HasManyGetAssociationsMixinOptions) => Promise<Model[]>
type GetOne<Model> = (options?: HasOneGetAssociationMixinOptions) => Promise<Model>

class Account extends Model {
  public uuid!: NonNullable<string>
  public name!: string | null
  public url!: string | null
  public status!: "UNKNOWN" | "ENABLED" | "DISABLED" | "DELETED" | "ACTIVATING" | null
  public shortName!: NonNullable<string>
  public webOrigin!: boolean | null
  public webPrivate!: boolean | null
  public webPublic!: boolean | null
  public stripeId!: string | null
  public accountSubscriptionId!: string | null
  public accountLicenseSubscriptionItemId!: string | null
  public accountType!: NonNullable<string>
  public overQuotaUntil!: Date | null
  public subscriptionItem!: string | null
  public lastBillingClose!: Date | null
  public violationStatus!: NonNullable<string>
  public pendingCancellation!: NonNullable<string>
  public additionalLicensesSubItemId!: string | null
  public connectedDomain!: string | null
  public domainAssociationId!: string | null
  public bio!: string | null
  public publicFeatured!: boolean | null
  public icon!: string | null
  public trialStatus!: NonNullable<"NONE" | "ACCOUNT" | "BILLING" | "ACTIVE" | "CANCELED" | "ENDED" | "UPGRADED" | "VIOLATION" | "INELIGIBLE" | "VOIDED">
  public trialUntil!: Date | null
  public defaultAppLicenseInvoicePaymentsAllowed!: NonNullable<boolean>
  public accountLicenseInvoiceLineItemId!: string | null
  public googleMapsPlaceId!: string | null
  public googleMapsPlaceIdUpdatedAt!: Date | null
  public contactUrl!: string | null
  public verifiedPartner!: NonNullable<boolean>
  public verifiedPremierePartner!: NonNullable<boolean>
  public apiAccessOverride!: NonNullable<boolean>
  public twitterHandle!: string | null
  public linkedInHandle!: string | null
  public youtubeHandle!: string | null
  public stripeConnectAccountId!: string | null
  public developerId!: string | null
  public specialFeatures!: Array<SpecialFeatureFlag> | null
  public accountSubscriptionScheduleId!: string | null
  public adEnabled!: boolean | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getUsers!: GetMany<User_Account>
  public setUsers!: HasManySetAssociationsMixin<User_Account, string>
  public addUser!: HasManyAddAssociationMixin<User_Account, string>
  public addUsers!: HasManyAddAssociationsMixin<User_Account, string>
  public createUser!: HasManyCreateAssociationMixin<User_Account>
  public removeUser!: HasManyRemoveAssociationMixin<User_Account, string>
  public removeUsers!: HasManyRemoveAssociationsMixin<User_Account, string>
  public hasUser!: HasManyHasAssociationMixin<User_Account, string>
  public hasUsers!: HasManyHasAssociationsMixin<User_Account, string>
  public countUsers!: HasManyCountAssociationsMixin

  public Users?: User_Account[]

  public getApps!: GetMany<App>
  public setApps!: HasManySetAssociationsMixin<App, string>
  public addApp!: HasManyAddAssociationMixin<App, string>
  public addApps!: HasManyAddAssociationsMixin<App, string>
  public createApp!: HasManyCreateAssociationMixin<App>
  public removeApp!: HasManyRemoveAssociationMixin<App, string>
  public removeApps!: HasManyRemoveAssociationsMixin<App, string>
  public hasApp!: HasManyHasAssociationMixin<App, string>
  public hasApps!: HasManyHasAssociationsMixin<App, string>
  public countApps!: HasManyCountAssociationsMixin

  public Apps?: App[]

  public getPolicyViolations!: GetMany<PolicyViolation>
  public setPolicyViolations!: HasManySetAssociationsMixin<PolicyViolation, string>
  public addPolicyViolation!: HasManyAddAssociationMixin<PolicyViolation, string>
  public addPolicyViolations!: HasManyAddAssociationsMixin<PolicyViolation, string>
  public createPolicyViolation!: HasManyCreateAssociationMixin<PolicyViolation>
  public removePolicyViolation!: HasManyRemoveAssociationMixin<PolicyViolation, string>
  public removePolicyViolations!: HasManyRemoveAssociationsMixin<PolicyViolation, string>
  public hasPolicyViolation!: HasManyHasAssociationMixin<PolicyViolation, string>
  public hasPolicyViolations!: HasManyHasAssociationsMixin<PolicyViolation, string>
  public countPolicyViolations!: HasManyCountAssociationsMixin

  public PolicyViolations?: PolicyViolation[]

  public getContracts!: GetMany<Contract>
  public setContracts!: HasManySetAssociationsMixin<Contract, string>
  public addContract!: HasManyAddAssociationMixin<Contract, string>
  public addContracts!: HasManyAddAssociationsMixin<Contract, string>
  public createContract!: HasManyCreateAssociationMixin<Contract>
  public removeContract!: HasManyRemoveAssociationMixin<Contract, string>
  public removeContracts!: HasManyRemoveAssociationsMixin<Contract, string>
  public hasContract!: HasManyHasAssociationMixin<Contract, string>
  public hasContracts!: HasManyHasAssociationsMixin<Contract, string>
  public countContracts!: HasManyCountAssociationsMixin

  public Contracts?: Contract[]

  public getAccountContractAgreements!: GetMany<AccountContractAgreement>
  public setAccountContractAgreements!: HasManySetAssociationsMixin<AccountContractAgreement, string>
  public addAccountContractAgreement!: HasManyAddAssociationMixin<AccountContractAgreement, string>
  public addAccountContractAgreements!: HasManyAddAssociationsMixin<AccountContractAgreement, string>
  public createAccountContractAgreement!: HasManyCreateAssociationMixin<AccountContractAgreement>
  public removeAccountContractAgreement!: HasManyRemoveAssociationMixin<AccountContractAgreement, string>
  public removeAccountContractAgreements!: HasManyRemoveAssociationsMixin<AccountContractAgreement, string>
  public hasAccountContractAgreement!: HasManyHasAssociationMixin<AccountContractAgreement, string>
  public hasAccountContractAgreements!: HasManyHasAssociationsMixin<AccountContractAgreement, string>
  public countAccountContractAgreements!: HasManyCountAssociationsMixin

  public AccountContractAgreements?: AccountContractAgreement[]

  public getApiKeys!: GetMany<ApiKey>
  public setApiKeys!: HasManySetAssociationsMixin<ApiKey, string>
  public addApiKey!: HasManyAddAssociationMixin<ApiKey, string>
  public addApiKeys!: HasManyAddAssociationsMixin<ApiKey, string>
  public createApiKey!: HasManyCreateAssociationMixin<ApiKey>
  public removeApiKey!: HasManyRemoveAssociationMixin<ApiKey, string>
  public removeApiKeys!: HasManyRemoveAssociationsMixin<ApiKey, string>
  public hasApiKey!: HasManyHasAssociationMixin<ApiKey, string>
  public hasApiKeys!: HasManyHasAssociationsMixin<ApiKey, string>
  public countApiKeys!: HasManyCountAssociationsMixin

  public ApiKeys?: ApiKey[]

  public getAccountShortNames!: GetMany<AccountShortName>
  public setAccountShortNames!: HasManySetAssociationsMixin<AccountShortName, string>
  public addAccountShortName!: HasManyAddAssociationMixin<AccountShortName, string>
  public addAccountShortNames!: HasManyAddAssociationsMixin<AccountShortName, string>
  public createAccountShortName!: HasManyCreateAssociationMixin<AccountShortName>
  public removeAccountShortName!: HasManyRemoveAssociationMixin<AccountShortName, string>
  public removeAccountShortNames!: HasManyRemoveAssociationsMixin<AccountShortName, string>
  public hasAccountShortName!: HasManyHasAssociationMixin<AccountShortName, string>
  public hasAccountShortNames!: HasManyHasAssociationsMixin<AccountShortName, string>
  public countAccountShortNames!: HasManyCountAssociationsMixin

  public AccountShortNames?: AccountShortName[]

  public getModules!: GetMany<Module>
  public setModules!: HasManySetAssociationsMixin<Module, string>
  public addModule!: HasManyAddAssociationMixin<Module, string>
  public addModules!: HasManyAddAssociationsMixin<Module, string>
  public createModule!: HasManyCreateAssociationMixin<Module>
  public removeModule!: HasManyRemoveAssociationMixin<Module, string>
  public removeModules!: HasManyRemoveAssociationsMixin<Module, string>
  public hasModule!: HasManyHasAssociationMixin<Module, string>
  public hasModules!: HasManyHasAssociationsMixin<Module, string>
  public countModules!: HasManyCountAssociationsMixin

  public Modules?: Module[]

  public getInvites!: GetMany<Invite>
  public setInvites!: HasManySetAssociationsMixin<Invite, string>
  public addInvite!: HasManyAddAssociationMixin<Invite, string>
  public addInvites!: HasManyAddAssociationsMixin<Invite, string>
  public createInvite!: HasManyCreateAssociationMixin<Invite>
  public removeInvite!: HasManyRemoveAssociationMixin<Invite, string>
  public removeInvites!: HasManyRemoveAssociationsMixin<Invite, string>
  public hasInvite!: HasManyHasAssociationMixin<Invite, string>
  public hasInvites!: HasManyHasAssociationsMixin<Invite, string>
  public countInvites!: HasManyCountAssociationsMixin

  public Invites?: Invite[]

  public getSharingApps!: GetMany<App>
  public setSharingApps!: HasManySetAssociationsMixin<App, string>
  public addSharingApp!: HasManyAddAssociationMixin<App, string>
  public addSharingApps!: HasManyAddAssociationsMixin<App, string>
  public createSharingApp!: HasManyCreateAssociationMixin<App>
  public removeSharingApp!: HasManyRemoveAssociationMixin<App, string>
  public removeSharingApps!: HasManyRemoveAssociationsMixin<App, string>
  public hasSharingApp!: HasManyHasAssociationMixin<App, string>
  public hasSharingApps!: HasManyHasAssociationsMixin<App, string>
  public countSharingApps!: HasManyCountAssociationsMixin

  public SharingApps?: App[]

  public getExternalApps!: GetMany<App>
  public setExternalApps!: HasManySetAssociationsMixin<App, string>
  public addExternalApp!: HasManyAddAssociationMixin<App, string>
  public addExternalApps!: HasManyAddAssociationsMixin<App, string>
  public createExternalApp!: HasManyCreateAssociationMixin<App>
  public removeExternalApp!: HasManyRemoveAssociationMixin<App, string>
  public removeExternalApps!: HasManyRemoveAssociationsMixin<App, string>
  public hasExternalApp!: HasManyHasAssociationMixin<App, string>
  public hasExternalApps!: HasManyHasAssociationsMixin<App, string>
  public countExternalApps!: HasManyCountAssociationsMixin

  public ExternalApps?: App[]

  public getSharingPermissions!: GetMany<CrossAccountPermission>
  public setSharingPermissions!: HasManySetAssociationsMixin<CrossAccountPermission, string>
  public addSharingPermission!: HasManyAddAssociationMixin<CrossAccountPermission, string>
  public addSharingPermissions!: HasManyAddAssociationsMixin<CrossAccountPermission, string>
  public createSharingPermission!: HasManyCreateAssociationMixin<CrossAccountPermission>
  public removeSharingPermission!: HasManyRemoveAssociationMixin<CrossAccountPermission, string>
  public removeSharingPermissions!: HasManyRemoveAssociationsMixin<CrossAccountPermission, string>
  public hasSharingPermission!: HasManyHasAssociationMixin<CrossAccountPermission, string>
  public hasSharingPermissions!: HasManyHasAssociationsMixin<CrossAccountPermission, string>
  public countSharingPermissions!: HasManyCountAssociationsMixin

  public SharingPermissions?: CrossAccountPermission[]

  public getExternalPermissions!: GetMany<CrossAccountPermission>
  public setExternalPermissions!: HasManySetAssociationsMixin<CrossAccountPermission, string>
  public addExternalPermission!: HasManyAddAssociationMixin<CrossAccountPermission, string>
  public addExternalPermissions!: HasManyAddAssociationsMixin<CrossAccountPermission, string>
  public createExternalPermission!: HasManyCreateAssociationMixin<CrossAccountPermission>
  public removeExternalPermission!: HasManyRemoveAssociationMixin<CrossAccountPermission, string>
  public removeExternalPermissions!: HasManyRemoveAssociationsMixin<CrossAccountPermission, string>
  public hasExternalPermission!: HasManyHasAssociationMixin<CrossAccountPermission, string>
  public hasExternalPermissions!: HasManyHasAssociationsMixin<CrossAccountPermission, string>
  public countExternalPermissions!: HasManyCountAssociationsMixin

  public ExternalPermissions?: CrossAccountPermission[]

  public getAssetRequests!: GetMany<AssetRequest>
  public setAssetRequests!: HasManySetAssociationsMixin<AssetRequest, string>
  public addAssetRequest!: HasManyAddAssociationMixin<AssetRequest, string>
  public addAssetRequests!: HasManyAddAssociationsMixin<AssetRequest, string>
  public createAssetRequest!: HasManyCreateAssociationMixin<AssetRequest>
  public removeAssetRequest!: HasManyRemoveAssociationMixin<AssetRequest, string>
  public removeAssetRequests!: HasManyRemoveAssociationsMixin<AssetRequest, string>
  public hasAssetRequest!: HasManyHasAssociationMixin<AssetRequest, string>
  public hasAssetRequests!: HasManyHasAssociationsMixin<AssetRequest, string>
  public countAssetRequests!: HasManyCountAssociationsMixin

  public AssetRequests?: AssetRequest[]

  public getAssetGenerations!: GetMany<AssetGeneration>
  public setAssetGenerations!: HasManySetAssociationsMixin<AssetGeneration, string>
  public addAssetGeneration!: HasManyAddAssociationMixin<AssetGeneration, string>
  public addAssetGenerations!: HasManyAddAssociationsMixin<AssetGeneration, string>
  public createAssetGeneration!: HasManyCreateAssociationMixin<AssetGeneration>
  public removeAssetGeneration!: HasManyRemoveAssociationMixin<AssetGeneration, string>
  public removeAssetGenerations!: HasManyRemoveAssociationsMixin<AssetGeneration, string>
  public hasAssetGeneration!: HasManyHasAssociationMixin<AssetGeneration, string>
  public hasAssetGenerations!: HasManyHasAssociationsMixin<AssetGeneration, string>
  public countAssetGenerations!: HasManyCountAssociationsMixin

  public AssetGenerations?: AssetGeneration[]

  public getCreditGrants!: GetMany<CreditGrant>
  public setCreditGrants!: HasManySetAssociationsMixin<CreditGrant, string>
  public addCreditGrant!: HasManyAddAssociationMixin<CreditGrant, string>
  public addCreditGrants!: HasManyAddAssociationsMixin<CreditGrant, string>
  public createCreditGrant!: HasManyCreateAssociationMixin<CreditGrant>
  public removeCreditGrant!: HasManyRemoveAssociationMixin<CreditGrant, string>
  public removeCreditGrants!: HasManyRemoveAssociationsMixin<CreditGrant, string>
  public hasCreditGrant!: HasManyHasAssociationMixin<CreditGrant, string>
  public hasCreditGrants!: HasManyHasAssociationsMixin<CreditGrant, string>
  public countCreditGrants!: HasManyCountAssociationsMixin

  public CreditGrants?: CreditGrant[]

  public getFeatures!: GetMany<Feature>
  public setFeatures!: HasManySetAssociationsMixin<Feature, string>
  public addFeature!: HasManyAddAssociationMixin<Feature, string>
  public addFeatures!: HasManyAddAssociationsMixin<Feature, string>
  public createFeature!: HasManyCreateAssociationMixin<Feature>
  public removeFeature!: HasManyRemoveAssociationMixin<Feature, string>
  public removeFeatures!: HasManyRemoveAssociationsMixin<Feature, string>
  public hasFeature!: HasManyHasAssociationMixin<Feature, string>
  public hasFeatures!: HasManyHasAssociationsMixin<Feature, string>
  public countFeatures!: HasManyCountAssociationsMixin

  public Features?: Feature[]

  public getCreditBalanceTransactions!: GetMany<CreditBalanceTransaction>
  public setCreditBalanceTransactions!: HasManySetAssociationsMixin<CreditBalanceTransaction, string>
  public addCreditBalanceTransaction!: HasManyAddAssociationMixin<CreditBalanceTransaction, string>
  public addCreditBalanceTransactions!: HasManyAddAssociationsMixin<CreditBalanceTransaction, string>
  public createCreditBalanceTransaction!: HasManyCreateAssociationMixin<CreditBalanceTransaction>
  public removeCreditBalanceTransaction!: HasManyRemoveAssociationMixin<CreditBalanceTransaction, string>
  public removeCreditBalanceTransactions!: HasManyRemoveAssociationsMixin<CreditBalanceTransaction, string>
  public hasCreditBalanceTransaction!: HasManyHasAssociationMixin<CreditBalanceTransaction, string>
  public hasCreditBalanceTransactions!: HasManyHasAssociationsMixin<CreditBalanceTransaction, string>
  public countCreditBalanceTransactions!: HasManyCountAssociationsMixin

  public CreditBalanceTransactions?: CreditBalanceTransaction[]

  public getReferralCodes!: GetMany<ReferralCode>
  public setReferralCodes!: HasManySetAssociationsMixin<ReferralCode, string>
  public addReferralCode!: HasManyAddAssociationMixin<ReferralCode, string>
  public addReferralCodes!: HasManyAddAssociationsMixin<ReferralCode, string>
  public createReferralCode!: HasManyCreateAssociationMixin<ReferralCode>
  public removeReferralCode!: HasManyRemoveAssociationMixin<ReferralCode, string>
  public removeReferralCodes!: HasManyRemoveAssociationsMixin<ReferralCode, string>
  public hasReferralCode!: HasManyHasAssociationMixin<ReferralCode, string>
  public hasReferralCodes!: HasManyHasAssociationsMixin<ReferralCode, string>
  public countReferralCodes!: HasManyCountAssociationsMixin

  public ReferralCodes?: ReferralCode[]
}

class AccountContractAgreement extends Model {
  public AccountUuid!: NonNullable<string>
  public ContractUuid!: NonNullable<string>
  public acceptedBy!: NonNullable<string>
  public acceptedAt!: NonNullable<Date>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account

  public getContract!: GetOne<Contract>
  public setContract!: HasOneSetAssociationMixin<Contract, string>
  public createContract!: HasOneCreateAssociationMixin<Contract>

  public Contract?: Contract
}

class AccountShortName extends Model {
  public name!: NonNullable<string>
  public AccountUuid!: NonNullable<string>
  public status!: NonNullable<"ACTIVE" | "DELETED">
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account
}

class App extends Model {
  public uuid!: NonNullable<string>
  public status!: "UNKNOWN" | "ENABLED" | "DISABLED" | "DELETED" | null
  public appName!: string | null
  public appKey!: string | null
  public AccountUuid!: NonNullable<string>
  public createdBy!: string | null
  public keyTimestamp!: number | null
  public version!: string | null
  public prevEngine!: string | null
  public isWeb!: boolean | null
  public shortLink!: string | null
  public webUrl!: string | null
  public webOrigins!: string[] | null
  public isCommercial!: NonNullable<boolean>
  public isPublic!: boolean | null
  public webReviewRequestedBy!: string | null
  public webReviewStatus!: NonNullable<"UNKNOWN" | "PENDING" | "APPROVED" | "REJECTED" | "COMPLETED">
  public webVersionStaging!: string | null
  public webVersionReview!: string | null
  public webVersionProduction!: string | null
  public webBackingUuid!: string | null
  public passphrase!: string | null
  public subscriptionItem!: string | null
  public violationStatus!: NonNullable<string>
  public ContractUuid!: string | null
  public commercialStatus!: "DEMO" | "DEVELOP" | "LAUNCH" | "COMPLETE" | "CANCELED" | null
  public endingAt!: Date | null
  public subscriptionId!: string | null
  public usageSubscriptionItemId!: string | null
  public licenseSubscriptionItemId!: string | null
  public legacyAccountType!: string | null
  public campaignRedirectUrl!: string | null
  public devSubStartDate!: Date | null
  public devSubPlanId!: string | null
  public campaignSubStartDate!: Date | null
  public campaignSubPlanId!: string | null
  public launchPackageId!: string | null
  public appDescription!: string | null
  public coverImageId!: string | null
  public appTitle!: string | null
  public repoStatus!: NonNullable<"UNKNOWN" | "NONE" | "PRIVATE" | "PUBLIC">
  public repoLicenseMaster!: string | null
  public repoLicenseProd!: string | null
  public connectedDomain!: string | null
  public domainAssociationId!: string | null
  public buildSettingsSplashScreen!: NonNullable<"UNKNOWN" | "DEFAULT" | "DISABLED" | "DEMO" | "NONCOMMERCIAL" | "EDUCATIONAL" | "APP">
  public hasPwaEnabled!: NonNullable<boolean>
  public publicFeatured!: boolean | null
  public assetLimitOverrides!: string | null
  public hasRecurringLicense!: NonNullable<boolean>
  public licenseInvoiceLineItemId!: string | null
  public featuredPreviewDisabled!: NonNullable<boolean>
  public featuredDescriptionId!: string | null
  public featuredVideoUrl!: string | null
  public publishedAt!: Date | null
  public productionCommitHash!: string | null
  public repoId!: string | null
  public hostingType!: NonNullable<"UNSET" | "CLOUD_EDITOR" | "CLOUD_STUDIO" | "SELF" | "INTERNAL" | "AD">
  public defaultSimulatorSequence!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account

  public getContract!: GetOne<Contract>
  public setContract!: HasOneSetAssociationMixin<Contract, string>
  public createContract!: HasOneCreateAssociationMixin<Contract>

  public Contract?: Contract

  public getPwaInfo!: GetOne<PwaInfo>
  public setPwaInfo!: HasOneSetAssociationMixin<PwaInfo, string>
  public createPwaInfo!: HasOneCreateAssociationMixin<PwaInfo>

  public PwaInfo?: PwaInfo

  public getNaeInfos!: GetMany<NaeInfo>
  public setNaeInfos!: HasManySetAssociationsMixin<NaeInfo, string>
  public addNaeInfo!: HasManyAddAssociationMixin<NaeInfo, string>
  public addNaeInfos!: HasManyAddAssociationsMixin<NaeInfo, string>
  public createNaeInfo!: HasManyCreateAssociationMixin<NaeInfo>
  public removeNaeInfo!: HasManyRemoveAssociationMixin<NaeInfo, string>
  public removeNaeInfos!: HasManyRemoveAssociationsMixin<NaeInfo, string>
  public hasNaeInfo!: HasManyHasAssociationMixin<NaeInfo, string>
  public hasNaeInfos!: HasManyHasAssociationsMixin<NaeInfo, string>
  public countNaeInfos!: HasManyCountAssociationsMixin

  public NaeInfos?: NaeInfo[]

  public getContractItems!: GetMany<ContractItem>
  public setContractItems!: HasManySetAssociationsMixin<ContractItem, string>
  public addContractItem!: HasManyAddAssociationMixin<ContractItem, string>
  public addContractItems!: HasManyAddAssociationsMixin<ContractItem, string>
  public createContractItem!: HasManyCreateAssociationMixin<ContractItem>
  public removeContractItem!: HasManyRemoveAssociationMixin<ContractItem, string>
  public removeContractItems!: HasManyRemoveAssociationsMixin<ContractItem, string>
  public hasContractItem!: HasManyHasAssociationMixin<ContractItem, string>
  public hasContractItems!: HasManyHasAssociationsMixin<ContractItem, string>
  public countContractItems!: HasManyCountAssociationsMixin

  public ContractItems?: ContractItem[]

  public getPolicyViolations!: GetMany<PolicyViolation>
  public setPolicyViolations!: HasManySetAssociationsMixin<PolicyViolation, string>
  public addPolicyViolation!: HasManyAddAssociationMixin<PolicyViolation, string>
  public addPolicyViolations!: HasManyAddAssociationsMixin<PolicyViolation, string>
  public createPolicyViolation!: HasManyCreateAssociationMixin<PolicyViolation>
  public removePolicyViolation!: HasManyRemoveAssociationMixin<PolicyViolation, string>
  public removePolicyViolations!: HasManyRemoveAssociationsMixin<PolicyViolation, string>
  public hasPolicyViolation!: HasManyHasAssociationMixin<PolicyViolation, string>
  public hasPolicyViolations!: HasManyHasAssociationsMixin<PolicyViolation, string>
  public countPolicyViolations!: HasManyCountAssociationsMixin

  public PolicyViolations?: PolicyViolation[]

  public getImageTargets!: GetMany<ImageTarget>
  public setImageTargets!: HasManySetAssociationsMixin<ImageTarget, string>
  public addImageTarget!: HasManyAddAssociationMixin<ImageTarget, string>
  public addImageTargets!: HasManyAddAssociationsMixin<ImageTarget, string>
  public createImageTarget!: HasManyCreateAssociationMixin<ImageTarget>
  public removeImageTarget!: HasManyRemoveAssociationMixin<ImageTarget, string>
  public removeImageTargets!: HasManyRemoveAssociationsMixin<ImageTarget, string>
  public hasImageTarget!: HasManyHasAssociationMixin<ImageTarget, string>
  public hasImageTargets!: HasManyHasAssociationsMixin<ImageTarget, string>
  public countImageTargets!: HasManyCountAssociationsMixin

  public ImageTargets?: ImageTarget[]

  public getScheduledSubscriptions!: GetMany<ScheduledSubscription>
  public setScheduledSubscriptions!: HasManySetAssociationsMixin<ScheduledSubscription, string>
  public addScheduledSubscription!: HasManyAddAssociationMixin<ScheduledSubscription, string>
  public addScheduledSubscriptions!: HasManyAddAssociationsMixin<ScheduledSubscription, string>
  public createScheduledSubscription!: HasManyCreateAssociationMixin<ScheduledSubscription>
  public removeScheduledSubscription!: HasManyRemoveAssociationMixin<ScheduledSubscription, string>
  public removeScheduledSubscriptions!: HasManyRemoveAssociationsMixin<ScheduledSubscription, string>
  public hasScheduledSubscription!: HasManyHasAssociationMixin<ScheduledSubscription, string>
  public hasScheduledSubscriptions!: HasManyHasAssociationsMixin<ScheduledSubscription, string>
  public countScheduledSubscriptions!: HasManyCountAssociationsMixin

  public ScheduledSubscriptions?: ScheduledSubscription[]

  public getUser_App_Prefs!: GetMany<User_App_Pref>
  public setUser_App_Prefs!: HasManySetAssociationsMixin<User_App_Pref, string>
  public addUser_App_Pref!: HasManyAddAssociationMixin<User_App_Pref, string>
  public addUser_App_Prefs!: HasManyAddAssociationsMixin<User_App_Pref, string>
  public createUser_App_Pref!: HasManyCreateAssociationMixin<User_App_Pref>
  public removeUser_App_Pref!: HasManyRemoveAssociationMixin<User_App_Pref, string>
  public removeUser_App_Prefs!: HasManyRemoveAssociationsMixin<User_App_Pref, string>
  public hasUser_App_Pref!: HasManyHasAssociationMixin<User_App_Pref, string>
  public hasUser_App_Prefs!: HasManyHasAssociationsMixin<User_App_Pref, string>
  public countUser_App_Prefs!: HasManyCountAssociationsMixin

  public User_App_Prefs?: User_App_Pref[]

  public getAppTags!: GetMany<AppTag>
  public setAppTags!: HasManySetAssociationsMixin<AppTag, string>
  public addAppTag!: HasManyAddAssociationMixin<AppTag, string>
  public addAppTags!: HasManyAddAssociationsMixin<AppTag, string>
  public createAppTag!: HasManyCreateAssociationMixin<AppTag>
  public removeAppTag!: HasManyRemoveAssociationMixin<AppTag, string>
  public removeAppTags!: HasManyRemoveAssociationsMixin<AppTag, string>
  public hasAppTag!: HasManyHasAssociationMixin<AppTag, string>
  public hasAppTags!: HasManyHasAssociationsMixin<AppTag, string>
  public countAppTags!: HasManyCountAssociationsMixin

  public AppTags?: AppTag[]

  public getFeaturedAppImages!: GetMany<FeaturedAppImage>
  public setFeaturedAppImages!: HasManySetAssociationsMixin<FeaturedAppImage, string>
  public addFeaturedAppImage!: HasManyAddAssociationMixin<FeaturedAppImage, string>
  public addFeaturedAppImages!: HasManyAddAssociationsMixin<FeaturedAppImage, string>
  public createFeaturedAppImage!: HasManyCreateAssociationMixin<FeaturedAppImage>
  public removeFeaturedAppImage!: HasManyRemoveAssociationMixin<FeaturedAppImage, string>
  public removeFeaturedAppImages!: HasManyRemoveAssociationsMixin<FeaturedAppImage, string>
  public hasFeaturedAppImage!: HasManyHasAssociationMixin<FeaturedAppImage, string>
  public hasFeaturedAppImages!: HasManyHasAssociationsMixin<FeaturedAppImage, string>
  public countFeaturedAppImages!: HasManyCountAssociationsMixin

  public FeaturedAppImages?: FeaturedAppImage[]

  public getDiscoveryApp!: GetOne<DiscoveryApp>
  public setDiscoveryApp!: HasOneSetAssociationMixin<DiscoveryApp, string>
  public createDiscoveryApp!: HasOneCreateAssociationMixin<DiscoveryApp>

  public DiscoveryApp?: DiscoveryApp

  public getFromAccounts!: GetMany<Account>
  public setFromAccounts!: HasManySetAssociationsMixin<Account, string>
  public addFromAccount!: HasManyAddAssociationMixin<Account, string>
  public addFromAccounts!: HasManyAddAssociationsMixin<Account, string>
  public createFromAccount!: HasManyCreateAssociationMixin<Account>
  public removeFromAccount!: HasManyRemoveAssociationMixin<Account, string>
  public removeFromAccounts!: HasManyRemoveAssociationsMixin<Account, string>
  public hasFromAccount!: HasManyHasAssociationMixin<Account, string>
  public hasFromAccounts!: HasManyHasAssociationsMixin<Account, string>
  public countFromAccounts!: HasManyCountAssociationsMixin

  public FromAccounts?: Account[]

  public getToAccounts!: GetMany<Account>
  public setToAccounts!: HasManySetAssociationsMixin<Account, string>
  public addToAccount!: HasManyAddAssociationMixin<Account, string>
  public addToAccounts!: HasManyAddAssociationsMixin<Account, string>
  public createToAccount!: HasManyCreateAssociationMixin<Account>
  public removeToAccount!: HasManyRemoveAssociationMixin<Account, string>
  public removeToAccounts!: HasManyRemoveAssociationsMixin<Account, string>
  public hasToAccount!: HasManyHasAssociationMixin<Account, string>
  public hasToAccounts!: HasManyHasAssociationsMixin<Account, string>
  public countToAccounts!: HasManyCountAssociationsMixin

  public ToAccounts?: Account[]

  public getSharePermissions!: GetMany<CrossAccountPermission>
  public setSharePermissions!: HasManySetAssociationsMixin<CrossAccountPermission, string>
  public addSharePermission!: HasManyAddAssociationMixin<CrossAccountPermission, string>
  public addSharePermissions!: HasManyAddAssociationsMixin<CrossAccountPermission, string>
  public createSharePermission!: HasManyCreateAssociationMixin<CrossAccountPermission>
  public removeSharePermission!: HasManyRemoveAssociationMixin<CrossAccountPermission, string>
  public removeSharePermissions!: HasManyRemoveAssociationsMixin<CrossAccountPermission, string>
  public hasSharePermission!: HasManyHasAssociationMixin<CrossAccountPermission, string>
  public hasSharePermissions!: HasManyHasAssociationsMixin<CrossAccountPermission, string>
  public countSharePermissions!: HasManyCountAssociationsMixin

  public SharePermissions?: CrossAccountPermission[]

  public getDependencySets!: GetMany<DependencySet>
  public setDependencySets!: HasManySetAssociationsMixin<DependencySet, string>
  public addDependencySet!: HasManyAddAssociationMixin<DependencySet, string>
  public addDependencySets!: HasManyAddAssociationsMixin<DependencySet, string>
  public createDependencySet!: HasManyCreateAssociationMixin<DependencySet>
  public removeDependencySet!: HasManyRemoveAssociationMixin<DependencySet, string>
  public removeDependencySets!: HasManyRemoveAssociationsMixin<DependencySet, string>
  public hasDependencySet!: HasManyHasAssociationMixin<DependencySet, string>
  public hasDependencySets!: HasManyHasAssociationsMixin<DependencySet, string>
  public countDependencySets!: HasManyCountAssociationsMixin

  public DependencySets?: DependencySet[]

  public getAdSubmissions!: GetMany<AdSubmission>
  public setAdSubmissions!: HasManySetAssociationsMixin<AdSubmission, string>
  public addAdSubmission!: HasManyAddAssociationMixin<AdSubmission, string>
  public addAdSubmissions!: HasManyAddAssociationsMixin<AdSubmission, string>
  public createAdSubmission!: HasManyCreateAssociationMixin<AdSubmission>
  public removeAdSubmission!: HasManyRemoveAssociationMixin<AdSubmission, string>
  public removeAdSubmissions!: HasManyRemoveAssociationsMixin<AdSubmission, string>
  public hasAdSubmission!: HasManyHasAssociationMixin<AdSubmission, string>
  public hasAdSubmissions!: HasManyHasAssociationsMixin<AdSubmission, string>
  public countAdSubmissions!: HasManyCountAssociationsMixin

  public AdSubmissions?: AdSubmission[]

  public getWayspotAnchors!: GetMany<WayspotAnchor>
  public setWayspotAnchors!: HasManySetAssociationsMixin<WayspotAnchor, string>
  public addWayspotAnchor!: HasManyAddAssociationMixin<WayspotAnchor, string>
  public addWayspotAnchors!: HasManyAddAssociationsMixin<WayspotAnchor, string>
  public createWayspotAnchor!: HasManyCreateAssociationMixin<WayspotAnchor>
  public removeWayspotAnchor!: HasManyRemoveAssociationMixin<WayspotAnchor, string>
  public removeWayspotAnchors!: HasManyRemoveAssociationsMixin<WayspotAnchor, string>
  public hasWayspotAnchor!: HasManyHasAssociationMixin<WayspotAnchor, string>
  public hasWayspotAnchors!: HasManyHasAssociationsMixin<WayspotAnchor, string>
  public countWayspotAnchors!: HasManyCountAssociationsMixin

  public WayspotAnchors?: WayspotAnchor[]

  public getFeatures!: GetMany<Feature>
  public setFeatures!: HasManySetAssociationsMixin<Feature, string>
  public addFeature!: HasManyAddAssociationMixin<Feature, string>
  public addFeatures!: HasManyAddAssociationsMixin<Feature, string>
  public createFeature!: HasManyCreateAssociationMixin<Feature>
  public removeFeature!: HasManyRemoveAssociationMixin<Feature, string>
  public removeFeatures!: HasManyRemoveAssociationsMixin<Feature, string>
  public hasFeature!: HasManyHasAssociationMixin<Feature, string>
  public hasFeatures!: HasManyHasAssociationsMixin<Feature, string>
  public countFeatures!: HasManyCountAssociationsMixin

  public Features?: Feature[]
}

class Contract extends Model {
  public uuid!: NonNullable<string>
  public AccountUuid!: string | null
  public createdBy!: NonNullable<number>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
  public expirationDate!: NonNullable<Date>
  public isReusable!: NonNullable<boolean>
  public name!: NonNullable<string>
  public startDate!: NonNullable<Date>
  public signedDate!: Date | null
  public hasPublicityRights!: NonNullable<boolean>
  public pdfPath!: NonNullable<string>
  public isAvailableAsCanned!: boolean | null
  public invoicePaymentsAllowed!: boolean | null
  public isRecurringContract!: NonNullable<boolean>

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account

  public getContractItems!: GetMany<ContractItem>
  public setContractItems!: HasManySetAssociationsMixin<ContractItem, string>
  public addContractItem!: HasManyAddAssociationMixin<ContractItem, string>
  public addContractItems!: HasManyAddAssociationsMixin<ContractItem, string>
  public createContractItem!: HasManyCreateAssociationMixin<ContractItem>
  public removeContractItem!: HasManyRemoveAssociationMixin<ContractItem, string>
  public removeContractItems!: HasManyRemoveAssociationsMixin<ContractItem, string>
  public hasContractItem!: HasManyHasAssociationMixin<ContractItem, string>
  public hasContractItems!: HasManyHasAssociationsMixin<ContractItem, string>
  public countContractItems!: HasManyCountAssociationsMixin

  public ContractItems?: ContractItem[]

  public getContractTemplates!: GetMany<ContractTemplate>
  public setContractTemplates!: HasManySetAssociationsMixin<ContractTemplate, string>
  public addContractTemplate!: HasManyAddAssociationMixin<ContractTemplate, string>
  public addContractTemplates!: HasManyAddAssociationsMixin<ContractTemplate, string>
  public createContractTemplate!: HasManyCreateAssociationMixin<ContractTemplate>
  public removeContractTemplate!: HasManyRemoveAssociationMixin<ContractTemplate, string>
  public removeContractTemplates!: HasManyRemoveAssociationsMixin<ContractTemplate, string>
  public hasContractTemplate!: HasManyHasAssociationMixin<ContractTemplate, string>
  public hasContractTemplates!: HasManyHasAssociationsMixin<ContractTemplate, string>
  public countContractTemplates!: HasManyCountAssociationsMixin

  public ContractTemplates?: ContractTemplate[]

  public getApps!: GetMany<App>
  public setApps!: HasManySetAssociationsMixin<App, string>
  public addApp!: HasManyAddAssociationMixin<App, string>
  public addApps!: HasManyAddAssociationsMixin<App, string>
  public createApp!: HasManyCreateAssociationMixin<App>
  public removeApp!: HasManyRemoveAssociationMixin<App, string>
  public removeApps!: HasManyRemoveAssociationsMixin<App, string>
  public hasApp!: HasManyHasAssociationMixin<App, string>
  public hasApps!: HasManyHasAssociationsMixin<App, string>
  public countApps!: HasManyCountAssociationsMixin

  public Apps?: App[]

  public getAccountContractAgreements!: GetMany<AccountContractAgreement>
  public setAccountContractAgreements!: HasManySetAssociationsMixin<AccountContractAgreement, string>
  public addAccountContractAgreement!: HasManyAddAssociationMixin<AccountContractAgreement, string>
  public addAccountContractAgreements!: HasManyAddAssociationsMixin<AccountContractAgreement, string>
  public createAccountContractAgreement!: HasManyCreateAssociationMixin<AccountContractAgreement>
  public removeAccountContractAgreement!: HasManyRemoveAssociationMixin<AccountContractAgreement, string>
  public removeAccountContractAgreements!: HasManyRemoveAssociationsMixin<AccountContractAgreement, string>
  public hasAccountContractAgreement!: HasManyHasAssociationMixin<AccountContractAgreement, string>
  public hasAccountContractAgreements!: HasManyHasAssociationsMixin<AccountContractAgreement, string>
  public countAccountContractAgreements!: HasManyCountAssociationsMixin

  public AccountContractAgreements?: AccountContractAgreement[]
}

class ContractItem extends Model {
  public uuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
  public AppUuid!: NonNullable<string>
  public ContractUuid!: NonNullable<string>
  public amount!: NonNullable<number>
  public startDate!: NonNullable<Date>
  public endDate!: NonNullable<Date>
  public canceledAt!: Date | null
  public stripeInvoiceId!: NonNullable<string>
  public stripeInvoiceItemId!: NonNullable<string>

  public getContract!: GetOne<Contract>
  public setContract!: HasOneSetAssociationMixin<Contract, string>
  public createContract!: HasOneCreateAssociationMixin<Contract>

  public Contract?: Contract

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App
}

class ContractTemplate extends Model {
  public uuid!: NonNullable<string>
  public name!: string | null
  public description!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
  public ContractUuid!: NonNullable<string>
  public amount!: NonNullable<number>
  public interval!: NonNullable<"DAY" | "WEEK" | "MONTH">
  public intervalCount!: NonNullable<number>
  public daysUntilDue!: NonNullable<number>
  public type!: NonNullable<"DEMO" | "DEV" | "DEV_EXT" | "CAMPAIGN" | "CAMPAIGN_EXT">
  public billingScheme!: NonNullable<"PER_UNIT" | "TIERED">
  public stripeSubPlanId!: string | null
  public stripeUsagePlanId!: string | null
  public packageId!: string | null

  public getContract!: GetOne<Contract>
  public setContract!: HasOneSetAssociationMixin<Contract, string>
  public createContract!: HasOneCreateAssociationMixin<Contract>

  public Contract?: Contract

  public getContractTiers!: GetMany<ContractTier>
  public setContractTiers!: HasManySetAssociationsMixin<ContractTier, string>
  public addContractTier!: HasManyAddAssociationMixin<ContractTier, string>
  public addContractTiers!: HasManyAddAssociationsMixin<ContractTier, string>
  public createContractTier!: HasManyCreateAssociationMixin<ContractTier>
  public removeContractTier!: HasManyRemoveAssociationMixin<ContractTier, string>
  public removeContractTiers!: HasManyRemoveAssociationsMixin<ContractTier, string>
  public hasContractTier!: HasManyHasAssociationMixin<ContractTier, string>
  public hasContractTiers!: HasManyHasAssociationsMixin<ContractTier, string>
  public countContractTiers!: HasManyCountAssociationsMixin

  public ContractTiers?: ContractTier[]
}

class ContractTier extends Model {
  public uuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
  public flat_amount!: NonNullable<number>
  public unit_amount!: NonNullable<number>
  public up_to!: number | null
  public ContractTemplateUuid!: NonNullable<string>

  public getContractTemplate!: GetOne<ContractTemplate>
  public setContractTemplate!: HasOneSetAssociationMixin<ContractTemplate, string>
  public createContractTemplate!: HasOneCreateAssociationMixin<ContractTemplate>

  public ContractTemplate?: ContractTemplate
}

class ImageTarget extends Model {
  public uuid!: NonNullable<string>
  public type!: NonNullable<"UNSPECIFIED" | "PLANAR" | "CYLINDER" | "CONICAL" | "SCAN">
  public AppUuid!: string | null
  public name!: string | null
  public originalImagePath!: string | null
  public imagePath!: string | null
  public luminanceImagePath!: string | null
  public thumbnailImagePath!: string | null
  public geometryTexturePath!: string | null
  public scanDataPath!: string | null
  public status!: "UNKNOWN" | "ENABLED" | "DISABLED" | "DELETED" | "DRAFT" | "TAKEN_DOWN" | null
  public userMetadata!: string | null
  public moveable!: NonNullable<boolean>
  public physicalWidthInMeters!: number | null
  public metadata!: string | null
  public isRotated!: NonNullable<boolean>
  public userMetadataIsJson!: NonNullable<boolean>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App
}

class Invite extends Model {
  public AccountUuid!: NonNullable<string>
  public email!: NonNullable<string>
  public from!: string | null
  public token!: string | null
  public ReferralCodeUuid!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account

  public getReferralCode!: GetOne<ReferralCode>
  public setReferralCode!: HasOneSetAssociationMixin<ReferralCode, string>
  public createReferralCode!: HasOneCreateAssociationMixin<ReferralCode>

  public ReferralCode?: ReferralCode
}

class NaeInfo extends Model {
  public uuid!: NonNullable<string>
  public AppUuid!: NonNullable<string>
  public platform!: NonNullable<"ANDROID" | "IOS">
  public publisher!: string | null
  public displayName!: string | null
  public bundleId!: string | null
  public iconId!: string | null
  public launchScreenIconId!: string | null
  public permissions!: Permissions | null
  public lastBuiltVersionName!: string | null
  public lastBuiltVersionCode!: number | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App
}

class NaePackagerBuild extends Model {
  public version!: NonNullable<string>
  public timestamp!: NonNullable<Date>
  public status!: "COMPLETED" | "FAILED" | "PENDING" | null
  public buildType!: "branch" | "main" | null
  public byteSize!: number | null
  public filename!: string | null
  public sha256!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
}

class NaePackagerChannel extends Model {
  public name!: NonNullable<"branch" | "beta" | "release" | "dev">
  public version!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
}

class NaePackagerVersionState extends Model {
  public name!: NonNullable<"main" | "branch">
  public major!: NonNullable<number>
  public minor!: NonNullable<number>
  public patch!: NonNullable<number>
  public main!: NonNullable<number>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
}

class PolicyViolation extends Model {
  public uuid!: NonNullable<string>
  public violationType!: NonNullable<string>
  public status!: NonNullable<string>
  public resolvedAt!: Date | null
  public AccountUuid!: string | null
  public AppUuid!: string | null
  public creatorId!: NonNullable<number>
  public resolverId!: number | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
}

class PwaInfo extends Model {
  public uuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
  public name!: string | null
  public shortName!: string | null
  public iconId!: string | null
  public backgroundColor!: string | null
  public themeColor!: string | null
  public AppUuid!: NonNullable<string>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App
}

class ScheduledSubscription extends Model {
  public uuid!: NonNullable<string>
  public AppUuid!: NonNullable<string>
  public startDate!: NonNullable<Date>
  public planId!: NonNullable<string>
  public paymentSource!: string | null
  public collectionMethod!: NonNullable<"send_invoice" | "charge_automatically">
  public completedAt!: Date | null
  public scheduledStatus!: NonNullable<"DEVELOP" | "LAUNCH">
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App
}

class User_Account extends Model {
  public UserUuid!: NonNullable<string>
  public AccountUuid!: NonNullable<string>
  public role!: "OWNER" | "ADMIN" | "DEV" | "BILLMANAGER" | null
  public handle!: string | null
  public firebaseId!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account
}

class User_App_Pref extends Model {
  public UserUuid!: NonNullable<string>
  public AppUuid!: NonNullable<string>
  public accessDate!: Date | null
  public activeBrowser!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App
}

class ApiKey extends Model {
  public uuid!: NonNullable<string>
  public secretKey!: NonNullable<string>
  public status!: NonNullable<"ENABLED" | "DISABLED" | "DELETED">
  public name!: NonNullable<string>
  public AccountUuid!: NonNullable<string>
  public fullAccountAccess!: boolean | null
  public keyId!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account
}

class AppTag extends Model {
  public uuid!: NonNullable<string>
  public name!: NonNullable<string>
  public restricted!: NonNullable<boolean>
  public blocked!: NonNullable<boolean>
  public suggestedTag!: NonNullable<boolean>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getApps!: GetMany<App>
  public setApps!: HasManySetAssociationsMixin<App, string>
  public addApp!: HasManyAddAssociationMixin<App, string>
  public addApps!: HasManyAddAssociationsMixin<App, string>
  public createApp!: HasManyCreateAssociationMixin<App>
  public removeApp!: HasManyRemoveAssociationMixin<App, string>
  public removeApps!: HasManyRemoveAssociationsMixin<App, string>
  public hasApp!: HasManyHasAssociationMixin<App, string>
  public hasApps!: HasManyHasAssociationsMixin<App, string>
  public countApps!: HasManyCountAssociationsMixin

  public Apps?: App[]

  public getModules!: GetMany<Module>
  public setModules!: HasManySetAssociationsMixin<Module, string>
  public addModule!: HasManyAddAssociationMixin<Module, string>
  public addModules!: HasManyAddAssociationsMixin<Module, string>
  public createModule!: HasManyCreateAssociationMixin<Module>
  public removeModule!: HasManyRemoveAssociationMixin<Module, string>
  public removeModules!: HasManyRemoveAssociationsMixin<Module, string>
  public hasModule!: HasManyHasAssociationMixin<Module, string>
  public hasModules!: HasManyHasAssociationsMixin<Module, string>
  public countModules!: HasManyCountAssociationsMixin

  public Modules?: Module[]
}

class AppTagMap extends Model {
  public uuid!: NonNullable<string>
  public AppUuid!: NonNullable<string>
  public AppTagUuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App

  public getAppTag!: GetOne<AppTag>
  public setAppTag!: HasOneSetAssociationMixin<AppTag, string>
  public createAppTag!: HasOneCreateAssociationMixin<AppTag>

  public AppTag?: AppTag
}

class FeaturedAppImage extends Model {
  public uuid!: NonNullable<string>
  public AppUuid!: string | null
  public ModuleUuid!: string | null
  public objectId!: NonNullable<string>
  public status!: NonNullable<"DRAFT" | "FEATURED" | "DELETED" | "DISABLED">
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App

  public getModule!: GetOne<Module>
  public setModule!: HasOneSetAssociationMixin<Module, string>
  public createModule!: HasOneCreateAssociationMixin<Module>

  public Module?: Module
}

class Module extends Model {
  public uuid!: NonNullable<string>
  public status!: NonNullable<"ACTIVE" | "DELETED">
  public AccountUuid!: NonNullable<string>
  public name!: NonNullable<string>
  public repoId!: string | null
  public title!: string | null
  public description!: string | null
  public coverImageId!: string | null
  public publicFeatured!: NonNullable<boolean>
  public featuredDescriptionId!: string | null
  public featuredVideoUrl!: string | null
  public compatibility!: NonNullable<"UNSET" | "CLOUD_EDITOR_ONLY" | "SELF_ONLY" | "ANY" | "CLOUD_STUDIO_ONLY" | "EDITOR_SELF" | "SELF_STUDIO" | "EDITOR_STUDIO">
  public repoVisibility!: NonNullable<"PRIVATE" | "PUBLIC">
  public archived!: NonNullable<boolean>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account

  public getModuleUsers!: GetMany<ModuleUser>
  public setModuleUsers!: HasManySetAssociationsMixin<ModuleUser, string>
  public addModuleUser!: HasManyAddAssociationMixin<ModuleUser, string>
  public addModuleUsers!: HasManyAddAssociationsMixin<ModuleUser, string>
  public createModuleUser!: HasManyCreateAssociationMixin<ModuleUser>
  public removeModuleUser!: HasManyRemoveAssociationMixin<ModuleUser, string>
  public removeModuleUsers!: HasManyRemoveAssociationsMixin<ModuleUser, string>
  public hasModuleUser!: HasManyHasAssociationMixin<ModuleUser, string>
  public hasModuleUsers!: HasManyHasAssociationsMixin<ModuleUser, string>
  public countModuleUsers!: HasManyCountAssociationsMixin

  public ModuleUsers?: ModuleUser[]

  public getFeaturedAppImages!: GetMany<FeaturedAppImage>
  public setFeaturedAppImages!: HasManySetAssociationsMixin<FeaturedAppImage, string>
  public addFeaturedAppImage!: HasManyAddAssociationMixin<FeaturedAppImage, string>
  public addFeaturedAppImages!: HasManyAddAssociationsMixin<FeaturedAppImage, string>
  public createFeaturedAppImage!: HasManyCreateAssociationMixin<FeaturedAppImage>
  public removeFeaturedAppImage!: HasManyRemoveAssociationMixin<FeaturedAppImage, string>
  public removeFeaturedAppImages!: HasManyRemoveAssociationsMixin<FeaturedAppImage, string>
  public hasFeaturedAppImage!: HasManyHasAssociationMixin<FeaturedAppImage, string>
  public hasFeaturedAppImages!: HasManyHasAssociationsMixin<FeaturedAppImage, string>
  public countFeaturedAppImages!: HasManyCountAssociationsMixin

  public FeaturedAppImages?: FeaturedAppImage[]

  public getTags!: GetMany<AppTag>
  public setTags!: HasManySetAssociationsMixin<AppTag, string>
  public addTag!: HasManyAddAssociationMixin<AppTag, string>
  public addTags!: HasManyAddAssociationsMixin<AppTag, string>
  public createTag!: HasManyCreateAssociationMixin<AppTag>
  public removeTag!: HasManyRemoveAssociationMixin<AppTag, string>
  public removeTags!: HasManyRemoveAssociationsMixin<AppTag, string>
  public hasTag!: HasManyHasAssociationMixin<AppTag, string>
  public hasTags!: HasManyHasAssociationsMixin<AppTag, string>
  public countTags!: HasManyCountAssociationsMixin

  public Tags?: AppTag[]
}

class DiscoveryApp extends Model {
  public uuid!: NonNullable<string>
  public hidden!: boolean | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App
}

class ModuleUser extends Model {
  public UserUuid!: NonNullable<string>
  public ModuleUuid!: NonNullable<string>
  public accessDate!: Date | null
  public activeBrowser!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getModule!: GetOne<Module>
  public setModule!: HasOneSetAssociationMixin<Module, string>
  public createModule!: HasOneCreateAssociationMixin<Module>

  public Module?: Module
}

class CrossAccountPermission extends Model {
  public uuid!: NonNullable<string>
  public FromAccountUuid!: NonNullable<string>
  public ToAccountUuid!: NonNullable<string>
  public AppUuid!: string | null
  public status!: "INVITED" | "ACTIVE" | "DELETED" | null
  public inviteToken!: string | null
  public invitedAt!: Date | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App

  public getFromAccount!: GetOne<Account>
  public setFromAccount!: HasOneSetAssociationMixin<Account, string>
  public createFromAccount!: HasOneCreateAssociationMixin<Account>

  public FromAccount?: Account

  public getToAccount!: GetOne<Account>
  public setToAccount!: HasOneSetAssociationMixin<Account, string>
  public createToAccount!: HasOneCreateAssociationMixin<Account>

  public ToAccount?: Account
}

class DependencySet extends Model {
  public uuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
  public AppUuid!: NonNullable<string>
  public data!: NonNullable<{dependenciesById: DependenciesById}>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App
}

class ModuleTagMap extends Model {
  public uuid!: NonNullable<string>
  public ModuleUuid!: NonNullable<string>
  public AppTagUuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getModule!: GetOne<Module>
  public setModule!: HasOneSetAssociationMixin<Module, string>
  public createModule!: HasOneCreateAssociationMixin<Module>

  public Module?: Module

  public getAppTag!: GetOne<AppTag>
  public setAppTag!: HasOneSetAssociationMixin<AppTag, string>
  public createAppTag!: HasOneCreateAssociationMixin<AppTag>

  public AppTag?: AppTag
}

class AdSubmission extends Model {
  public uuid!: NonNullable<string>
  public commitId!: NonNullable<string>
  public AppUuid!: NonNullable<string>
  public requestUuid!: string | null
  public reviewStatus!: NonNullable<"APPROVED" | "PENDING" | "REJECTED">
  public url!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
  public reviewedAt!: Date | null
  public decisionExplanation!: string | null

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App
}

class AppEngagementMetric extends Model {
  public dt!: NonNullable<Date>
  public appKey!: NonNullable<string>
  public meanPageTimeMs!: NonNullable<number>
  public totalSessions!: NonNullable<number>
  public sampledSessions!: NonNullable<number>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App
}

class User extends Model {
  public uuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
  public crmId!: string | null
  public newsletterId!: string | null
  public emailVerifyTime!: Date | null
  public handle!: string | null
  public themeSettings!: Partial<UserEditorSettings> | null
  public tosAgreements!: TermsAgreements | null
  public primaryContactEmail!: NonNullable<string>
  public givenName!: string | null
  public familyName!: string | null
  public locale!: NonNullable<string>
  public phoneNumber!: string | null
  public phoneNumberVerified!: boolean | null
  public emailVerified!: boolean | null
  public hasFirstTimePublished!: boolean | null
  public profileIcon!: string | null
  public latestActivityDate!: Date | null
  public lastSeenReleasePopupId!: string | null

  public getPlayerUser!: GetOne<PlayerUser>
  public setPlayerUser!: HasOneSetAssociationMixin<PlayerUser, string>
  public createPlayerUser!: HasOneCreateAssociationMixin<PlayerUser>

  public PlayerUser?: PlayerUser

  public getAssetRequests!: GetMany<AssetRequest>
  public setAssetRequests!: HasManySetAssociationsMixin<AssetRequest, string>
  public addAssetRequest!: HasManyAddAssociationMixin<AssetRequest, string>
  public addAssetRequests!: HasManyAddAssociationsMixin<AssetRequest, string>
  public createAssetRequest!: HasManyCreateAssociationMixin<AssetRequest>
  public removeAssetRequest!: HasManyRemoveAssociationMixin<AssetRequest, string>
  public removeAssetRequests!: HasManyRemoveAssociationsMixin<AssetRequest, string>
  public hasAssetRequest!: HasManyHasAssociationMixin<AssetRequest, string>
  public hasAssetRequests!: HasManyHasAssociationsMixin<AssetRequest, string>
  public countAssetRequests!: HasManyCountAssociationsMixin

  public AssetRequests?: AssetRequest[]

  public getAssetGenerations!: GetMany<AssetGeneration>
  public setAssetGenerations!: HasManySetAssociationsMixin<AssetGeneration, string>
  public addAssetGeneration!: HasManyAddAssociationMixin<AssetGeneration, string>
  public addAssetGenerations!: HasManyAddAssociationsMixin<AssetGeneration, string>
  public createAssetGeneration!: HasManyCreateAssociationMixin<AssetGeneration>
  public removeAssetGeneration!: HasManyRemoveAssociationMixin<AssetGeneration, string>
  public removeAssetGenerations!: HasManyRemoveAssociationsMixin<AssetGeneration, string>
  public hasAssetGeneration!: HasManyHasAssociationMixin<AssetGeneration, string>
  public hasAssetGenerations!: HasManyHasAssociationsMixin<AssetGeneration, string>
  public countAssetGenerations!: HasManyCountAssociationsMixin

  public AssetGenerations?: AssetGeneration[]

  public getReferralCodeRedemptions!: GetMany<ReferralCodeRedemption>
  public setReferralCodeRedemptions!: HasManySetAssociationsMixin<ReferralCodeRedemption, string>
  public addReferralCodeRedemption!: HasManyAddAssociationMixin<ReferralCodeRedemption, string>
  public addReferralCodeRedemptions!: HasManyAddAssociationsMixin<ReferralCodeRedemption, string>
  public createReferralCodeRedemption!: HasManyCreateAssociationMixin<ReferralCodeRedemption>
  public removeReferralCodeRedemption!: HasManyRemoveAssociationMixin<ReferralCodeRedemption, string>
  public removeReferralCodeRedemptions!: HasManyRemoveAssociationsMixin<ReferralCodeRedemption, string>
  public hasReferralCodeRedemption!: HasManyHasAssociationMixin<ReferralCodeRedemption, string>
  public hasReferralCodeRedemptions!: HasManyHasAssociationsMixin<ReferralCodeRedemption, string>
  public countReferralCodeRedemptions!: HasManyCountAssociationsMixin

  public ReferralCodeRedemptions?: ReferralCodeRedemption[]

  public getUserLoginMethods!: GetMany<UserLoginMethods>
  public setUserLoginMethods!: HasManySetAssociationsMixin<UserLoginMethods, string>
  public addUserLoginMethod!: HasManyAddAssociationMixin<UserLoginMethods, string>
  public addUserLoginMethods!: HasManyAddAssociationsMixin<UserLoginMethods, string>
  public createUserLoginMethod!: HasManyCreateAssociationMixin<UserLoginMethods>
  public removeUserLoginMethod!: HasManyRemoveAssociationMixin<UserLoginMethods, string>
  public removeUserLoginMethods!: HasManyRemoveAssociationsMixin<UserLoginMethods, string>
  public hasUserLoginMethod!: HasManyHasAssociationMixin<UserLoginMethods, string>
  public hasUserLoginMethods!: HasManyHasAssociationsMixin<UserLoginMethods, string>
  public countUserLoginMethods!: HasManyCountAssociationsMixin

  public UserLoginMethods?: UserLoginMethods[]
}

class UserLoginMethods extends Model {
  public uuid!: NonNullable<string>
  public UserUuid!: NonNullable<string>
  public email!: NonNullable<string>
  public provider!: NonNullable<"EMAIL" | "GOOGLE" | "APPLE">
  public thirdPartyUserId!: NonNullable<string>
  public createdAt!: Date | null
  public updatedAt!: NonNullable<Date>
  public deletedAt!: Date | null

  public getUser!: GetOne<User>
  public setUser!: HasOneSetAssociationMixin<User, string>
  public createUser!: HasOneCreateAssociationMixin<User>

  public User?: User
}

class PlayerUser extends Model {
  public UserUuid!: NonNullable<string>
  public playerId!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getUser!: GetOne<User>
  public setUser!: HasOneSetAssociationMixin<User, string>
  public createUser!: HasOneCreateAssociationMixin<User>

  public User?: User
}

class AssetRequest extends Model {
  public uuid!: NonNullable<string>
  public AccountUuid!: NonNullable<string>
  public UserUuid!: NonNullable<string>
  public ParentRequestUuid!: string | null
  public totalActionQuantity!: number | null
  public input!: Partial<GenerateRequestInput> | null
  public type!: "TEXT_TO_IMAGE" | "IMAGE_TO_IMAGE" | "IMAGE_TO_MESH" | "MESH_TO_ANIMATION" | null
  public status!: NonNullable<"REQUESTED" | "PROCESSING" | "SUCCESS" | "FAILED">
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getUser!: GetOne<User>
  public setUser!: HasOneSetAssociationMixin<User, string>
  public createUser!: HasOneCreateAssociationMixin<User>

  public User?: User

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account

  public getAssetGenerations!: GetMany<AssetGeneration>
  public setAssetGenerations!: HasManySetAssociationsMixin<AssetGeneration, string>
  public addAssetGeneration!: HasManyAddAssociationMixin<AssetGeneration, string>
  public addAssetGenerations!: HasManyAddAssociationsMixin<AssetGeneration, string>
  public createAssetGeneration!: HasManyCreateAssociationMixin<AssetGeneration>
  public removeAssetGeneration!: HasManyRemoveAssociationMixin<AssetGeneration, string>
  public removeAssetGenerations!: HasManyRemoveAssociationsMixin<AssetGeneration, string>
  public hasAssetGeneration!: HasManyHasAssociationMixin<AssetGeneration, string>
  public hasAssetGenerations!: HasManyHasAssociationsMixin<AssetGeneration, string>
  public countAssetGenerations!: HasManyCountAssociationsMixin

  public AssetGenerations?: AssetGeneration[]

  public getCreditBalanceTransactions!: GetMany<CreditBalanceTransaction>
  public setCreditBalanceTransactions!: HasManySetAssociationsMixin<CreditBalanceTransaction, string>
  public addCreditBalanceTransaction!: HasManyAddAssociationMixin<CreditBalanceTransaction, string>
  public addCreditBalanceTransactions!: HasManyAddAssociationsMixin<CreditBalanceTransaction, string>
  public createCreditBalanceTransaction!: HasManyCreateAssociationMixin<CreditBalanceTransaction>
  public removeCreditBalanceTransaction!: HasManyRemoveAssociationMixin<CreditBalanceTransaction, string>
  public removeCreditBalanceTransactions!: HasManyRemoveAssociationsMixin<CreditBalanceTransaction, string>
  public hasCreditBalanceTransaction!: HasManyHasAssociationMixin<CreditBalanceTransaction, string>
  public hasCreditBalanceTransactions!: HasManyHasAssociationsMixin<CreditBalanceTransaction, string>
  public countCreditBalanceTransactions!: HasManyCountAssociationsMixin

  public CreditBalanceTransactions?: CreditBalanceTransaction[]

  public getAssetRequest!: GetOne<AssetRequest>
  public setAssetRequest!: HasOneSetAssociationMixin<AssetRequest, string>
  public createAssetRequest!: HasOneCreateAssociationMixin<AssetRequest>

  public AssetRequest?: AssetRequest

  public getChildRequests!: GetMany<AssetRequest>
  public setChildRequests!: HasManySetAssociationsMixin<AssetRequest, string>
  public addChildRequest!: HasManyAddAssociationMixin<AssetRequest, string>
  public addChildRequests!: HasManyAddAssociationsMixin<AssetRequest, string>
  public createChildRequest!: HasManyCreateAssociationMixin<AssetRequest>
  public removeChildRequest!: HasManyRemoveAssociationMixin<AssetRequest, string>
  public removeChildRequests!: HasManyRemoveAssociationsMixin<AssetRequest, string>
  public hasChildRequest!: HasManyHasAssociationMixin<AssetRequest, string>
  public hasChildRequests!: HasManyHasAssociationsMixin<AssetRequest, string>
  public countChildRequests!: HasManyCountAssociationsMixin

  public ChildRequests?: AssetRequest[]
}

class AssetGeneration extends Model {
  public uuid!: NonNullable<string>
  public RequestUuid!: NonNullable<string>
  public AccountUuid!: NonNullable<string>
  public UserUuid!: NonNullable<string>
  public assetType!: NonNullable<"IMAGE" | "MESH">
  public modelName!: NonNullable<string>
  public prompt!: string | null
  public negativePrompt!: string | null
  public style!: string | null
  public seed!: NonNullable<string>
  public metadata!: Record<string, unknown> | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getUser!: GetOne<User>
  public setUser!: HasOneSetAssociationMixin<User, string>
  public createUser!: HasOneCreateAssociationMixin<User>

  public User?: User

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account

  public getAssetRequest!: GetOne<AssetRequest>
  public setAssetRequest!: HasOneSetAssociationMixin<AssetRequest, string>
  public createAssetRequest!: HasOneCreateAssociationMixin<AssetRequest>

  public AssetRequest?: AssetRequest
}

class WayspotAnchor extends Model {
  public uuid!: NonNullable<string>
  public AppUuid!: NonNullable<string>
  public approxLat!: NonNullable<number>
  public approxLng!: NonNullable<number>
  public name!: NonNullable<string>
  public payload!: NonNullable<string>
  public poiId!: NonNullable<string>
  public poiHashedId!: string | null
  public poiTitle!: string | null
  public poiImage!: string | null
  public nodeId!: NonNullable<string>
  public spaceId!: string | null
  public hasMegaModeMesh!: boolean | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App
}

class CreditGrant extends Model {
  public uuid!: NonNullable<string>
  public AccountUuid!: NonNullable<string>
  public category!: NonNullable<"PAID_PLAN" | "PAID_TOPUP" | "FREE_STANDARD" | "FREE_PROMOTION">
  public quantity!: NonNullable<number>
  public remainingQuantity!: NonNullable<number>
  public unitPrice!: NonNullable<number>
  public totalPrice!: NonNullable<number>
  public unitValue!: NonNullable<number>
  public totalValue!: NonNullable<number>
  public effectiveAt!: NonNullable<Date>
  public expiresAt!: NonNullable<Date>
  public status!: NonNullable<"GRANTED" | "VOIDED">
  public anchorDate!: Date | null
  public description!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account

  public getTransactions!: GetMany<Transaction>
  public setTransactions!: HasManySetAssociationsMixin<Transaction, string>
  public addTransaction!: HasManyAddAssociationMixin<Transaction, string>
  public addTransactions!: HasManyAddAssociationsMixin<Transaction, string>
  public createTransaction!: HasManyCreateAssociationMixin<Transaction>
  public removeTransaction!: HasManyRemoveAssociationMixin<Transaction, string>
  public removeTransactions!: HasManyRemoveAssociationsMixin<Transaction, string>
  public hasTransaction!: HasManyHasAssociationMixin<Transaction, string>
  public hasTransactions!: HasManyHasAssociationsMixin<Transaction, string>
  public countTransactions!: HasManyCountAssociationsMixin

  public Transactions?: Transaction[]

  public getCreditBalanceTransactions!: GetMany<CreditBalanceTransaction>
  public setCreditBalanceTransactions!: HasManySetAssociationsMixin<CreditBalanceTransaction, string>
  public addCreditBalanceTransaction!: HasManyAddAssociationMixin<CreditBalanceTransaction, string>
  public addCreditBalanceTransactions!: HasManyAddAssociationsMixin<CreditBalanceTransaction, string>
  public createCreditBalanceTransaction!: HasManyCreateAssociationMixin<CreditBalanceTransaction>
  public removeCreditBalanceTransaction!: HasManyRemoveAssociationMixin<CreditBalanceTransaction, string>
  public removeCreditBalanceTransactions!: HasManyRemoveAssociationsMixin<CreditBalanceTransaction, string>
  public hasCreditBalanceTransaction!: HasManyHasAssociationMixin<CreditBalanceTransaction, string>
  public hasCreditBalanceTransactions!: HasManyHasAssociationsMixin<CreditBalanceTransaction, string>
  public countCreditBalanceTransactions!: HasManyCountAssociationsMixin

  public CreditBalanceTransactions?: CreditBalanceTransaction[]
}

class Feature extends Model {
  public uuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
  public category!: NonNullable<"ACCOUNT" | "APP">
  public featureName!: NonNullable<string>
  public optionName!: NonNullable<string>
  public status!: NonNullable<"ENABLED" | "DISABLED" | "VOIDED">
  public billingType!: NonNullable<"RECURRING" | "ONE_TIME">
  public subscriptionId!: string | null
  public subscriptionItemId!: string | null
  public subscriptionScheduleId!: string | null
  public subscriptionEndsAt!: Date | null

  public getAccounts!: GetMany<Account>
  public setAccounts!: HasManySetAssociationsMixin<Account, string>
  public addAccount!: HasManyAddAssociationMixin<Account, string>
  public addAccounts!: HasManyAddAssociationsMixin<Account, string>
  public createAccount!: HasManyCreateAssociationMixin<Account>
  public removeAccount!: HasManyRemoveAssociationMixin<Account, string>
  public removeAccounts!: HasManyRemoveAssociationsMixin<Account, string>
  public hasAccount!: HasManyHasAssociationMixin<Account, string>
  public hasAccounts!: HasManyHasAssociationsMixin<Account, string>
  public countAccounts!: HasManyCountAssociationsMixin

  public Accounts?: Account[]

  public getApps!: GetMany<App>
  public setApps!: HasManySetAssociationsMixin<App, string>
  public addApp!: HasManyAddAssociationMixin<App, string>
  public addApps!: HasManyAddAssociationsMixin<App, string>
  public createApp!: HasManyCreateAssociationMixin<App>
  public removeApp!: HasManyRemoveAssociationMixin<App, string>
  public removeApps!: HasManyRemoveAssociationsMixin<App, string>
  public hasApp!: HasManyHasAssociationMixin<App, string>
  public hasApps!: HasManyHasAssociationsMixin<App, string>
  public countApps!: HasManyCountAssociationsMixin

  public Apps?: App[]

  public getTransactions!: GetMany<Transaction>
  public setTransactions!: HasManySetAssociationsMixin<Transaction, string>
  public addTransaction!: HasManyAddAssociationMixin<Transaction, string>
  public addTransactions!: HasManyAddAssociationsMixin<Transaction, string>
  public createTransaction!: HasManyCreateAssociationMixin<Transaction>
  public removeTransaction!: HasManyRemoveAssociationMixin<Transaction, string>
  public removeTransactions!: HasManyRemoveAssociationsMixin<Transaction, string>
  public hasTransaction!: HasManyHasAssociationMixin<Transaction, string>
  public hasTransactions!: HasManyHasAssociationsMixin<Transaction, string>
  public countTransactions!: HasManyCountAssociationsMixin

  public Transactions?: Transaction[]
}

class Transaction extends Model {
  public uuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>
  public AccountUuid!: NonNullable<string>
  public productId!: NonNullable<string>
  public priceId!: NonNullable<string>
  public invoiceId!: NonNullable<string>
  public invoiceItemId!: string | null
  public invoiceLineItemId!: NonNullable<string>

  public getFeatures!: GetMany<Feature>
  public setFeatures!: HasManySetAssociationsMixin<Feature, string>
  public addFeature!: HasManyAddAssociationMixin<Feature, string>
  public addFeatures!: HasManyAddAssociationsMixin<Feature, string>
  public createFeature!: HasManyCreateAssociationMixin<Feature>
  public removeFeature!: HasManyRemoveAssociationMixin<Feature, string>
  public removeFeatures!: HasManyRemoveAssociationsMixin<Feature, string>
  public hasFeature!: HasManyHasAssociationMixin<Feature, string>
  public hasFeatures!: HasManyHasAssociationsMixin<Feature, string>
  public countFeatures!: HasManyCountAssociationsMixin

  public Features?: Feature[]

  public getCreditGrants!: GetMany<CreditGrant>
  public setCreditGrants!: HasManySetAssociationsMixin<CreditGrant, string>
  public addCreditGrant!: HasManyAddAssociationMixin<CreditGrant, string>
  public addCreditGrants!: HasManyAddAssociationsMixin<CreditGrant, string>
  public createCreditGrant!: HasManyCreateAssociationMixin<CreditGrant>
  public removeCreditGrant!: HasManyRemoveAssociationMixin<CreditGrant, string>
  public removeCreditGrants!: HasManyRemoveAssociationsMixin<CreditGrant, string>
  public hasCreditGrant!: HasManyHasAssociationMixin<CreditGrant, string>
  public hasCreditGrants!: HasManyHasAssociationsMixin<CreditGrant, string>
  public countCreditGrants!: HasManyCountAssociationsMixin

  public CreditGrants?: CreditGrant[]
}

class AccountFeatureMap extends Model {
  public uuid!: NonNullable<string>
  public AccountUuid!: NonNullable<string>
  public FeatureUuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account

  public getFeature!: GetOne<Feature>
  public setFeature!: HasOneSetAssociationMixin<Feature, string>
  public createFeature!: HasOneCreateAssociationMixin<Feature>

  public Feature?: Feature
}

class FeatureTransactionMap extends Model {
  public uuid!: NonNullable<string>
  public FeatureUuid!: NonNullable<string>
  public TransactionUuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getFeature!: GetOne<Feature>
  public setFeature!: HasOneSetAssociationMixin<Feature, string>
  public createFeature!: HasOneCreateAssociationMixin<Feature>

  public Feature?: Feature

  public getTransaction!: GetOne<Transaction>
  public setTransaction!: HasOneSetAssociationMixin<Transaction, string>
  public createTransaction!: HasOneCreateAssociationMixin<Transaction>

  public Transaction?: Transaction
}

class CreditGrantTransactionMap extends Model {
  public uuid!: NonNullable<string>
  public CreditGrantUuid!: NonNullable<string>
  public TransactionUuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getCreditGrant!: GetOne<CreditGrant>
  public setCreditGrant!: HasOneSetAssociationMixin<CreditGrant, string>
  public createCreditGrant!: HasOneCreateAssociationMixin<CreditGrant>

  public CreditGrant?: CreditGrant

  public getTransaction!: GetOne<Transaction>
  public setTransaction!: HasOneSetAssociationMixin<Transaction, string>
  public createTransaction!: HasOneCreateAssociationMixin<Transaction>

  public Transaction?: Transaction
}

class CreditBalanceTransaction extends Model {
  public uuid!: NonNullable<string>
  public AccountUuid!: NonNullable<string>
  public type!: NonNullable<"BUY" | "GRANT" | "REDEEM" | "REFUND" | "ADJUST">
  public description!: string | null
  public UserUuid!: string | null
  public CreditGrantUuid!: NonNullable<string>
  public quantity!: NonNullable<number>
  public value!: NonNullable<number>
  public CreditServicePricingUuid!: string | null
  public totalActionQuantity!: NonNullable<number>
  public totalActionValue!: NonNullable<number>
  public AssetRequestUuid!: string | null
  public redeemStatus!: "PENDING" | "COMPLETED" | "FAILED" | "TIMED_OUT" | null
  public requestId!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account

  public getCreditGrant!: GetOne<CreditGrant>
  public setCreditGrant!: HasOneSetAssociationMixin<CreditGrant, string>
  public createCreditGrant!: HasOneCreateAssociationMixin<CreditGrant>

  public CreditGrant?: CreditGrant

  public getAssetRequest!: GetOne<AssetRequest>
  public setAssetRequest!: HasOneSetAssociationMixin<AssetRequest, string>
  public createAssetRequest!: HasOneCreateAssociationMixin<AssetRequest>

  public AssetRequest?: AssetRequest
}

class CreditServicePricing extends Model {
  public uuid!: NonNullable<string>
  public feature!: NonNullable<"ASSET_GEN" | "NAE">
  public requestType!: NonNullable<"TEXT_TO_IMAGE" | "IMAGE_TO_IMAGE" | "IMAGE_TO_MESH" | "MESH_TO_ANIMATION" | "ANDROID" | "IOS" | "HTML">
  public requestPrice!: NonNullable<number>
  public AiModelUuid!: string | null
  public status!: NonNullable<"ACTIVE" | "INACTIVE" | "QA">
  public UserUuid!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getUser!: GetOne<User>
  public setUser!: HasOneSetAssociationMixin<User, string>
  public createUser!: HasOneCreateAssociationMixin<User>

  public User?: User

  public getAiModel!: GetOne<AiModel>
  public setAiModel!: HasOneSetAssociationMixin<AiModel, string>
  public createAiModel!: HasOneCreateAssociationMixin<AiModel>

  public AiModel?: AiModel
}

class ReferralCode extends Model {
  public uuid!: NonNullable<string>
  public code!: NonNullable<string>
  public AccountUuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public deletedAt!: Date | null
  public updatedAt!: NonNullable<Date>

  public getAccount!: GetOne<Account>
  public setAccount!: HasOneSetAssociationMixin<Account, string>
  public createAccount!: HasOneCreateAssociationMixin<Account>

  public Account?: Account

  public getRedemptions!: GetMany<ReferralCodeRedemption>
  public setRedemptions!: HasManySetAssociationsMixin<ReferralCodeRedemption, string>
  public addRedemption!: HasManyAddAssociationMixin<ReferralCodeRedemption, string>
  public addRedemptions!: HasManyAddAssociationsMixin<ReferralCodeRedemption, string>
  public createRedemption!: HasManyCreateAssociationMixin<ReferralCodeRedemption>
  public removeRedemption!: HasManyRemoveAssociationMixin<ReferralCodeRedemption, string>
  public removeRedemptions!: HasManyRemoveAssociationsMixin<ReferralCodeRedemption, string>
  public hasRedemption!: HasManyHasAssociationMixin<ReferralCodeRedemption, string>
  public hasRedemptions!: HasManyHasAssociationsMixin<ReferralCodeRedemption, string>
  public countRedemptions!: HasManyCountAssociationsMixin

  public Redemptions?: ReferralCodeRedemption[]

  public getInvites!: GetMany<Invite>
  public setInvites!: HasManySetAssociationsMixin<Invite, string>
  public addInvite!: HasManyAddAssociationMixin<Invite, string>
  public addInvites!: HasManyAddAssociationsMixin<Invite, string>
  public createInvite!: HasManyCreateAssociationMixin<Invite>
  public removeInvite!: HasManyRemoveAssociationMixin<Invite, string>
  public removeInvites!: HasManyRemoveAssociationsMixin<Invite, string>
  public hasInvite!: HasManyHasAssociationMixin<Invite, string>
  public hasInvites!: HasManyHasAssociationsMixin<Invite, string>
  public countInvites!: HasManyCountAssociationsMixin

  public Invites?: Invite[]
}

class ReferralCodeReward extends Model {
  public uuid!: NonNullable<string>
  public name!: NonNullable<string>
  public referrerCreditAmount!: NonNullable<number>
  public refereeCreditAmount!: NonNullable<number>
  public isActive!: boolean | null
  public createdAt!: Date | null
  public updatedAt!: NonNullable<Date>

  public getRedemptions!: GetMany<ReferralCodeRedemption>
  public setRedemptions!: HasManySetAssociationsMixin<ReferralCodeRedemption, string>
  public addRedemption!: HasManyAddAssociationMixin<ReferralCodeRedemption, string>
  public addRedemptions!: HasManyAddAssociationsMixin<ReferralCodeRedemption, string>
  public createRedemption!: HasManyCreateAssociationMixin<ReferralCodeRedemption>
  public removeRedemption!: HasManyRemoveAssociationMixin<ReferralCodeRedemption, string>
  public removeRedemptions!: HasManyRemoveAssociationsMixin<ReferralCodeRedemption, string>
  public hasRedemption!: HasManyHasAssociationMixin<ReferralCodeRedemption, string>
  public hasRedemptions!: HasManyHasAssociationsMixin<ReferralCodeRedemption, string>
  public countRedemptions!: HasManyCountAssociationsMixin

  public Redemptions?: ReferralCodeRedemption[]
}

class ReferralCodeRedemption extends Model {
  public uuid!: NonNullable<string>
  public ReferralCodeUuid!: NonNullable<string>
  public ReferralCodeRewardUuid!: NonNullable<string>
  public UserUuid!: NonNullable<string>
  public createdAt!: Date | null
  public source!: NonNullable<"SIGNUP" | "EMAIL" | "UNKNOWN">
  public status!: NonNullable<"PENDING" | "PAID" | "REJECTED">
  public updatedAt!: NonNullable<Date>

  public getReferralCode!: GetOne<ReferralCode>
  public setReferralCode!: HasOneSetAssociationMixin<ReferralCode, string>
  public createReferralCode!: HasOneCreateAssociationMixin<ReferralCode>

  public ReferralCode?: ReferralCode

  public getReward!: GetOne<ReferralCodeReward>
  public setReward!: HasOneSetAssociationMixin<ReferralCodeReward, string>
  public createReward!: HasOneCreateAssociationMixin<ReferralCodeReward>

  public Reward?: ReferralCodeReward

  public getUser!: GetOne<User>
  public setUser!: HasOneSetAssociationMixin<User, string>
  public createUser!: HasOneCreateAssociationMixin<User>

  public User?: User
}

class AiModel extends Model {
  public uuid!: NonNullable<string>
  public serviceProvider!: NonNullable<string>
  public modelProvider!: NonNullable<string>
  public modelFamily!: NonNullable<string>
  public modelId!: NonNullable<string>
  public status!: NonNullable<"ACTIVE" | "INACTIVE" | "QA">
  public UserUuid!: string | null
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getUser!: GetOne<User>
  public setUser!: HasOneSetAssociationMixin<User, string>
  public createUser!: HasOneCreateAssociationMixin<User>

  public User?: User

  public getCreditServicePricings!: GetMany<CreditServicePricing>
  public setCreditServicePricings!: HasManySetAssociationsMixin<CreditServicePricing, string>
  public addCreditServicePricing!: HasManyAddAssociationMixin<CreditServicePricing, string>
  public addCreditServicePricings!: HasManyAddAssociationsMixin<CreditServicePricing, string>
  public createCreditServicePricing!: HasManyCreateAssociationMixin<CreditServicePricing>
  public removeCreditServicePricing!: HasManyRemoveAssociationMixin<CreditServicePricing, string>
  public removeCreditServicePricings!: HasManyRemoveAssociationsMixin<CreditServicePricing, string>
  public hasCreditServicePricing!: HasManyHasAssociationMixin<CreditServicePricing, string>
  public hasCreditServicePricings!: HasManyHasAssociationsMixin<CreditServicePricing, string>
  public countCreditServicePricings!: HasManyCountAssociationsMixin

  public CreditServicePricings?: CreditServicePricing[]
}

class AppFeatureMap extends Model {
  public uuid!: NonNullable<string>
  public AppUuid!: NonNullable<string>
  public FeatureUuid!: NonNullable<string>
  public createdAt!: NonNullable<Date>
  public updatedAt!: NonNullable<Date>

  public getApp!: GetOne<App>
  public setApp!: HasOneSetAssociationMixin<App, string>
  public createApp!: HasOneCreateAssociationMixin<App>

  public App?: App

  public getFeature!: GetOne<Feature>
  public setFeature!: HasOneSetAssociationMixin<Feature, string>
  public createFeature!: HasOneCreateAssociationMixin<Feature>

  public Feature?: Feature
}

export {
  Account,
  AccountContractAgreement,
  AccountShortName,
  App,
  Contract,
  ContractItem,
  ContractTemplate,
  ContractTier,
  ImageTarget,
  Invite,
  NaeInfo,
  NaePackagerBuild,
  NaePackagerChannel,
  NaePackagerVersionState,
  PolicyViolation,
  PwaInfo,
  ScheduledSubscription,
  User_Account,
  User_App_Pref,
  ApiKey,
  AppTag,
  AppTagMap,
  FeaturedAppImage,
  Module,
  DiscoveryApp,
  ModuleUser,
  CrossAccountPermission,
  DependencySet,
  ModuleTagMap,
  AdSubmission,
  AppEngagementMetric,
  User,
  UserLoginMethods,
  PlayerUser,
  AssetRequest,
  AssetGeneration,
  WayspotAnchor,
  CreditGrant,
  Feature,
  Transaction,
  AccountFeatureMap,
  FeatureTransactionMap,
  CreditGrantTransactionMap,
  CreditBalanceTransaction,
  CreditServicePricing,
  ReferralCode,
  ReferralCodeReward,
  ReferralCodeRedemption,
  AiModel,
  AppFeatureMap,
}
