package(default_visibility = [
    "//apps/client/internalqa/omniscope/native/views/features:__subpackages__",
])

filegroup(
    name = "cloud-reloc-test-data",
    srcs = [
        "cloud-reloc-test-map",
    ],
)
