const MAX_DESCRIPTION_LENGTH = 1024
const MAX_HEADER_COUNT = 16
const MAX_IDENTIFIER_LENGTH = 128
const MAX_LITERAL_LENGTH = 256
const MAX_ROUTES_PER_MODULE = 32
const MAX_ROUTES_PER_PROJECT = 64
const MAX_URL_LENGTH = 2048
const MAX_ENV_VARIABLE_COUNT = 16
const MAX_BACKEND_NAME_LENGTH = 256
const VALID_METHODS = new Set(['GET', 'PATCH', 'HEAD', 'POST', 'PUT', 'DELETE'])

const URL_CHARACTER_REGEX = /^[a-zA-Z0-9\-_/:?=.&%]*$/

export {
  MAX_DESCRIPTION_LENGTH,
  MAX_HEADER_COUNT,
  MAX_IDENTIFIER_LENGTH,
  MAX_LITERAL_LENGTH,
  MAX_ROUTES_PER_MODULE,
  MAX_ROUTES_PER_PROJECT,
  MAX_URL_LENGTH,
  VALID_METHODS,
  URL_CHARACTER_REGEX,
  MAX_ENV_VARIABLE_COUNT,
  MAX_BACKEND_NAME_LENGTH,
}
