// Copyright (c) 2021 8th Wall, Inc.
// Original Author: Rishi Parikh (rishi@8thwall.com)
//
// Calculates image target scores and visualizations for each sub category.

#include "c8/hpoint.h"
#include "c8/pixels/pixel-buffer.h"
#include "c8/pixels/pixels.h"
#include "c8/string.h"
#include "c8/vector.h"
#include "reality/engine/features/gr8-feature-shader.h"
#include "reality/engine/imagedetection/detection-image.h"

namespace c8 {

// calc-feature-score.cc

/**
 * featureCoverage creates a grid of scores to represent how many features are in the image
 * For each rectangle in the grid calculate the number of feature points in the region.
 * Each point is then scaled to a certain score ranging from 0.0 to 1.0.
 * The pixels object is updated to match the gridlike representation of feature scores.
 * @param DetectionImage<OrbFeature> the target image feature points.
 * @param gridRows the number of rows to split the image into
 * @param gridCols the number of columns to split the image into
 * @param pixels a pixel grid of gridRows X gridCols X 1 Float pixels to fill with score values.
 *
 */
void featureCoverage(
  const DetectionImage &detectionImage, OneChannelFloatPixels &pixels, int gridRows, int gridCols);

/**
 * Computes an image-level feature coverage score (in 0.0 to 100.0) from a feature coverage grid
 * computed using `featureCoverage`.
 * @param featureCoverageGrid a pixel grid of gridRows X gridCols X 1 Float pixels of feature
 * scores.
 */
float featureCoverageScore(const OneChannelFloatPixelBuffer &featureCoverageGrid);

/**
 * Renders a 2D image for visualization using a feature coverage grid computed using
 * `featureCoverage`
 * Registers a new shader called img-blur that applies a gaussian blur to create a heat-
 * map style texture.
 * Output image is shadded as black (bad) to red to yellow to white(good)
 * @param originalImage the target image.
 * @param featureCoverageGrid grid of scores from 0.0 to 1.0 representing number of feature points
 * in the region.
 */

RGBA8888PlanePixelBuffer visualizeFeatureScore(
  const RGBA8888PlanePixels &originalImage, const OneChannelFloatPixelBuffer &featureCoverageGrid);

// end calc-feature-score.cc

// calc-similarity-score.cc

/**
 * Uses hamming distance to calculate similarity scores between pairwise featurepoints.
 * A bad feature point pair is described as a hamming distance of less than 30.
 * @param DetectionImage<OrbFeature> representation of feature points of the target image.
 * @param poorHammingDist calculated cutoff for a good vs bad hamming distance.
 * Output Vector<HPoint2> a list of feature point locations with high similarity.
 */
Vector<HPoint2> computeSimiliarFeaturePoints(
  const DetectionImage &detectionImage, int poorHammingDist = 30);

/**
 * Generates a visualization of the similarity score. Overlays patches on top of the original
 * image at each location.
 * @param originalImage target image in RGBA8888PlanePixels representation.
 * @param patches in RGBA8888PlanePixels; an RGBA patch created using decaying alpha to
 * improve blending and visualization of multiple overlaid patches.
 * @param locations x, y locations of bad feature points generated by
 * `computeSimiliarFeaturePoints`
 * output RGBA8888PlanePixelBuffer representation of the generated scene.
 */
RGBA8888PlanePixelBuffer visualizeSimilarityScore(
  const RGBA8888PlanePixels &originalImage,
  const RGBA8888PlanePixels &patch,
  const Vector<HPoint2> &locations);

/*
 * Returns a score from 0.0 to 1.0 computed from <HPoint2> of bad locations.
 * This score is the proportion of good image features.
 * @param DetectionImage<OrbFeature> feature points computed from the target image
 * @param locations
 */
float similarityScore(const DetectionImage &detectionImage, const Vector<HPoint2> &locations);
// end calc-similarity-score.cc

// calc-detection-score.cc

/**
 * Places the original image target in various poses against a background image. Tests if the image
 * is recognizable in the scene and if the corners align with the correct position.
 * Returns a score between 0 to 100.
 * @param originalImage RGBA8888PlanePixels representation of an image to test detection.
 * @param background RGBA8888PlanePixels representation to use as the background.
 * @param detectedImages {out var} a pixel buffer vector containing the visualization for each of
 * the detection scenes. `detectedImages` will contain data and should not be overwritten.
 * @param detectionScore {out var} the output score.
 */
void calcDetectionScore(
  const RGBA8888PlanePixels &originalImage,
  const RGBA8888PlanePixels &background,
  Vector<RGBA8888PlanePixelBuffer> *detectedImages,
  float *detectionScore);
}  // namespace c8

// calc-detection-score.cc end

// extract-features.cc
DetectionImage extractFeatures(
  ConstRGBA8888PlanePixels pix, c8_PixelPinholeCameraModel k, Gr8FeatureShader *shader);
