import os
import os.path
import fileinput
import re
import sys
import glob
import getopt
import subprocess

def main(argv):
    BUILDIFIER = "buildifier"
    BUILD_FILE = "BUILD"
    FILE_TYPES = [".cc"]
    RULES = ["cc_library", "cc_binary", "cc_test"]
    PARSE_BUILD_RULES = os.path.join(os.path.dirname(__file__), "parse-build-rules.sh")
    START_TAG = "# START_AUTOGENERATED_RULES\n# Do not edit these rules manually, use inliner.\n"
    END_TAG = "\n# END_AUTOGENERATED_RULES"
    START_TAG_RE = re.compile(START_TAG)
    END_TAG_RE = re.compile(END_TAG)
    HASH_RE = re.compile(r'cc_end\(([x0-9a-z]+)\)')

    inPlace=True
    stdinSource=False

    try:
        opts, args = getopt.getopt(argv, 'si')
    except getopt.GetoptError as err:
        print(str(err, file=sys.stderr))
        sys.exit(2)

    # Output .cc changes to stdout if -s is specified.
    if ('-s', '') in opts:
        inPlace=False

    # Read source data from stdin. Requires exactly one source file is
    # specified to get path information.
    if ('-i', '') in opts:
        stdinSource=True

    # When reading from stdin, inPlace doesn't make sense.
    if stdinSource:
        inPlace=False

    if len(args) < 1:
        print("Must specify one or more files/directories", file=sys.stderr)
        sys.exit(2)

    def glob_files(build_dir):
        sources = []
        for file_type in FILE_TYPES:
            sources.extend(
                glob.glob(os.path.join(build_dir, '*' + file_type))
            )
        return sources

    # Find all source files with inliner rules.
    build_dirs = {}
    for arg in args:
        if os.path.isdir(arg):
            print("Inliner inputs must be %s files [%s]" % (', '.join(FILE_TYPES), arg), file=sys.stderr)
            sys.exit(2)
        elif not os.path.isfile(arg):
            # Cound not find a file with this name, abort.
            print("Could not find file [%s]" % arg, file=sys.stderr)
            sys.exit(2)
        else:
            if not arg.endswith(tuple(FILE_TYPES)):
                print("Inliner inputs must be %s files [%s]" % (', '.join(FILE_TYPES), arg), file=sys.stderr)
                sys.exit(2)
            directory = os.path.relpath(os.path.dirname(arg) or os.path.curdir)
            build_dirs.setdefault(
                directory,
                set()).add(arg)

    if stdinSource:
        if len(build_dirs) != 1 or len(next(iter(build_dirs.values()))) != 1:
            print("Must have exactly one source file when reading from stdin")
            sys.exit(2)

    for build_dir, allSources in build_dirs.items():
        if not allSources:
            print("No sources with build rules in [%s]" % build_dir, file=sys.stderr)
            sys.exit(2)

        if stdinSource:
            sources = list(allSources)
        else:
            # Do a quick grep to find sources *with* build rules.
            grep_sources = subprocess.Popen(
                [
                    'grep',
                    '-lE',
                    '^\s*(%s)\s*{' % '|'.join(RULES),
                ] + list(allSources),
                stdout=subprocess.PIPE).stdout.read().decode('utf-8').rstrip()
            sources = sorted(
              grep_sources.split('\n'),
              key=lambda name: os.path.splitext(os.path.basename(name))[0])

        # Convert to relative paths.
        sources = [os.path.relpath(x) for x in sources]

        build_file_path = os.path.join(build_dir, BUILD_FILE)

        if not os.path.isfile(build_file_path):
            if sources:
                try:
                    # Create the BUILD file.
                    open(build_file_path, 'w').close()
                    print("Created BUILD file [%s]" % build_file_path, file=sys.stderr)
                except:
                    print("Could not create BUILD file [%s]" % build_file_path, file=sys.stderr)
                    raise

            else:
                print("Could not find BUILD file [%s]" % build_file_path, file=sys.stderr)
                sys.exit(2)

        build_file = open(build_file_path, "r+")
        build_contents = build_file.read()

        stdinSourceData = b''

        if stdinSource:
            parseRulesProc = subprocess.Popen(
                 [PARSE_BUILD_RULES] + sources + ['-stdin'],
                 stdin=subprocess.PIPE,
                 stdout=subprocess.PIPE)
            stdinSourceData = sys.stdin.buffer.read()
            parseRulesProc.stdin.write(stdinSourceData)
            parseRulesProc.stdin.close()
            inline_rules_output = parseRulesProc.stdout.read().decode('utf-8').rstrip()
        else:
            inline_rules_output = subprocess.Popen(
                [PARSE_BUILD_RULES] + sources,
                stdout=subprocess.PIPE).stdout.read().decode('utf-8').rstrip()

        hashes = HASH_RE.findall(inline_rules_output)
        if len(hashes) != len(sources):
            print('One or more build rules is missing a hash from parse-build-rules', file=sys.stderr)
            sys.exit(2)

        inline_rules = inline_rules_output.split('\n\n')
        if len(inline_rules) != len(sources):
            print('One or more build rules is missing output from parse-build-rules', file=sys.stderr)
            sys.exit(2)

        sourceHashes = dict(zip(sources, hashes))
        sourceRules = dict(zip(sources, inline_rules))

        sourceRuleNameToSource = {}
        for source, inlineRule in sourceRules.items():
            try:
                ruleName = re.findall(r'    name = "([\w\.-]+)"', inlineRule)[0]
                if ruleName in sourceRuleNameToSource:
                    print("Duplicate 'name' attribute [%s] in [%s] and [%s]" % (
                        ruleName, sourceRuleNameToSource[ruleName], source), file=sys.stderr)
                    sys.exit(2)
                sourceRuleNameToSource[ruleName] = source
            except IndexError:
                print("No 'name' attribute in [%s]" % source, file=sys.stderr)
                sys.exit(2)

        startMatch = START_TAG_RE.search(build_contents)
        endMatch = END_TAG_RE.search(build_contents)
        contentsBegin = build_contents[0:startMatch.span()[0] if startMatch else -1]

        contentsAutoRules = (
            build_contents[startMatch and startMatch.span()[1] or -1:endMatch and endMatch.span()[0] or -1])
        contentsEnd = build_contents[endMatch and endMatch.span()[1] or -1:-1]

        previousRules = contentsAutoRules.split('\n\n')

        sortName = "^"
        existingRules = []
        for previousRule in previousRules:
            ruleName = None
            ruleFile = None
            try:
                ruleName = re.findall(r'    name = "([\w\.-]+)"', previousRule)[0]
            except IndexError:
                print("Warning: rule missing 'name' attribute in [%s]" % build_file_path, file=sys.stderr)

            try:
                ruleFile = re.findall(r'# file: ([\w\.-]+)', previousRule)[0]
            except IndexError:
                pass
            sortName = ruleFile or ruleName or sortName + '-1'
            existingRules.append((sortName, ruleFile, ruleName, previousRule))

        outputRules = []
        usedRules = set()
        for sortKey, ruleFile, ruleName, previousRule in existingRules:
            if ruleFile:
                fullRuleFile = os.path.normpath(os.path.join(build_dir, ruleFile))
                if fullRuleFile in sources:
                    # Replace the previous rule with the new rule.
                    if not fullRuleFile in usedRules:
                        outputRules.append((sortKey,
                            "# file: %s\n%s" % (os.path.basename(source), sourceRules[fullRuleFile])))
                        usedRules.add(fullRuleFile)
                elif fullRuleFile in allSources:
                    # File exists but has no inliner. Remove rule.
                    pass
                elif os.path.isfile(fullRuleFile):
                    # Keep the previous rule.
                    outputRules.append((ruleFile, previousRule))
                else:
                    # File doesn't exist, remove rule.
                    pass
            elif ruleName:
                lookupSource = sourceRuleNameToSource.get(ruleName, None)
                if lookupSource:
                    # We have a matching source, replace the previous rule with the new rule.
                    if not lookupSource in usedRules:
                        outputRules.append((sortKey,
                            "# file: %s\n%s" % (os.path.basename(source), sourceRules[lookupSource])))
                        usedRules.add(lookupSource)
                else:
                    # No matching source, keep the previous rule.
                    outputRules.append((sortKey, previousRule))
            else:
                # Keep the previous rule.
                outputRules.append((sortKey, previousRule))

        # Process the remaining rules.
        for source, inlineRule in sourceRules.items():
            if source not in usedRules:
                outputRules.append((os.path.basename(source),
                    "# file: %s\n%s" % (os.path.basename(source), inlineRule)))

        # Sort the rules alphabetically.
        outputRules.sort()

        # Remove any previous autogenerated rules.
        build_contents = contentsBegin + contentsEnd

        # Overwrite BUILD file with autogenerated rules.
        build_file.seek(0)
        build_file.write(build_contents)

        if outputRules:
             build_file.write(START_TAG)
             build_file.write(('\n\n').join(x[1] for x in outputRules))
             build_file.write(END_TAG + '\n')
             print('Updated %s' % build_file_path, file=sys.stderr)
        else:
             print('Removed autogen rules in %s' % build_file_path, file=sys.stderr)

        build_file.truncate()
        build_file.close()

        # Reformat using buildifier.
        subprocess.call([BUILDIFIER, build_file_path])

        def updateCcFile(sourceData):
            upgradeState = 0
            for line in sourceData:
                if line == '    "//bzl/inliner:rules",\n' or line == '    "//bzl/inliner:rules2",\n':
                    # Remove inliner deps.
                    pass
                elif line == '#include "bzl/inliner/rules.h"\n':
                    print('#include "bzl/inliner/rules2.h"')
                    upgradeState += 1
                elif upgradeState == 1 and line == '}\n':
                    print("}\n%s;" % hashSub)
                    upgradeState += 1
                else:
                    line = HASH_RE.sub(hashSub, line)
                    print(line, end='')

        # Make changes to the source file, adding the hash and upgrading rules1 to rules2.
        for source in sourceRules:
            ruleHash = sourceHashes[source]
            hashSub = 'cc_end(%s)' % ruleHash
            if stdinSource:
                updateCcFile(iter(stdinSourceData.decode('utf-8').splitlines(True)))
            else:
                with fileinput.input([source], inplace=inPlace) as file:
                    updateCcFile(file)


if __name__ == '__main__':
    main(sys.argv[1:])
