java_library(
    name = "exceptions-java",
    srcs = [
        "IllegalMobileAppKeyException.java",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//c8/annotations",
    ],
)
