load("//bzl/android:android.bzl", "android_java_library")

android_java_library(
    name = "opengl",
    srcs = [
        "ShaderUtil.java",
    ],
    visibility = [
        "//visibility:public",
    ],
)
