load("//bzl/js:js.bzl", "js_library")

js_library(
    name = "messaging",
    srcs = [
        "messaging.ts",
    ],
    visibility = [
        "//reality/app/nae:__subpackages__",
        "//reality/cloud:shared",
    ],
)
