filegroup(
    name = "worker-test-data",
    srcs = [
        "worker-test-0.js",
        "worker-test-1.js",
        "worker-test-2.js",
        "worker-test-3.js",
        "worker-test-4.js",
        "worker-test-5.js",
        "worker-test-6.js",
        "worker-test-7.js",
        "worker-test-8.js",
        "worker-test-module-import.js",
        "worker-test-module-script.js",
    ],
    visibility = ["//c8/dom:__subpackages__"],
)

filegroup(
    name = "worker-test-with-cache-data",
    srcs = [
        "worker-test-with-cache-0.js",
    ],
    visibility = ["//c8/dom:__subpackages__"],
)
