const MODULE_DEPENDENCY_VERSION = 1
const MAX_MODULE_TITLE_LENGTH = 100
const MAX_LAND_MESSAGE_LENGTH = 100
const MAX_MODULE_DESCRIPTION_LENGTH = 150
const MAX_MODULE_ALIAS_LENGTH = 70
const MODULE_ALIAS_PATTERN = /^[a-zA-Z0-9_-]+$/
const MODULE_NAME_PATTERN = /^[a-z0-9-]{4,128}$/
const MAX_DEPENDENCIES_PER_BUILD = 10
const DEFAULT_MODULES8_SCRIPT_URL = 'https://cdn.8thwall.com/web/hosting/modules8-llffcbe7.js'

enum AccessLevelEnum {
  owned = 'owned',
  public = 'public'
  // TODO (tri): add the following levels when implemented
  // purchased
}

// TODO (tri): update this number to actually reflect real UI design
const MAX_COVER_IMAGE_WIDTH = 1200
const MIN_COVER_IMAGE_WIDTH = 1200
const MIN_COVER_IMAGE_HEIGHT = 630

const COVER_IMAGE_PREVIEW_SIZES = {
  1200: [1200, 630],
  600: [600, 315],
  400: [400, 210],
}

const MAX_MODULE_FEATURED_IMAGE_COUNT = 10

export {
  AccessLevelEnum,
  MAX_COVER_IMAGE_WIDTH,
  MIN_COVER_IMAGE_HEIGHT,
  MIN_COVER_IMAGE_WIDTH,
  MODULE_ALIAS_PATTERN,
  MAX_MODULE_TITLE_LENGTH,
  MAX_LAND_MESSAGE_LENGTH,
  MAX_MODULE_DESCRIPTION_LENGTH,
  MAX_MODULE_ALIAS_LENGTH,
  MODULE_NAME_PATTERN,
  COVER_IMAGE_PREVIEW_SIZES,
  MODULE_DEPENDENCY_VERSION,
  MAX_DEPENDENCIES_PER_BUILD,
  DEFAULT_MODULES8_SCRIPT_URL,
  MAX_MODULE_FEATURED_IMAGE_COUNT,
}
