load("//bzl/js:js.bzl", "js_cli")

js_cli(
    name = "merge-request-stats",
    esnext = 1,
    main = [
        "merge-request-stats.ts",
    ],
    npm_rule = "@npm-apps-client-gitlab//:npm-apps-client-gitlab",
)
