const GET_TOPICS_ACTION_TYPE = 'CMS/GET_TOPICS'
const GET_POSTS_ACTION_TYPE = 'CMS/GET_POSTS'
const GET_MORE_POSTS_ACTION_TYPE = 'CMS/GET_MORE_POSTS'
const GET_POST_ACTION_TYPE = 'CMS/GET_POST'
const GET_START_ACTION_TYPE = 'CMS/START_ACTION'
const GET_STOP_ACTION_TYPE = 'CMS/STOP_ACTION'
const ACTION_FAILED = 'CMS/ACTION_FAILED'
const CLEAR_FAIL_ACTION = 'CMS/CLEAR_FAIL_ACTION'
const SEARCH_TOPICS_ACTION_TYPE = 'CMS/SEARCH_TOPICS'
const GET_HUBSPOT_CMS_PAGE_TYPE = 'CMS/GET_HUBSPOT_CMS_PAGE'

export {
  GET_TOPICS_ACTION_TYPE,
  GET_POSTS_ACTION_TYPE,
  GET_MORE_POSTS_ACTION_TYPE,
  GET_POST_ACTION_TYPE,
  GET_START_ACTION_TYPE,
  GET_STOP_ACTION_TYPE,
  ACTION_FAILED,
  CLEAR_FAIL_ACTION,
  SEARCH_TOPICS_ACTION_TYPE,
  GET_HUBSPOT_CMS_PAGE_TYPE,
}
